<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Reactivo límite – Natura Docens</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../bibliografia.html" rel="next">
<link href="../01_Generalidades/02_PlanDeArea.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../site_libs/quarto-contrib/quarto-project/edu-boxes.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reactivo límite</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Natura Docens</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/camilotayac/docere/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Natura-Docens.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Natura-Docens.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalidades</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Estructura del libro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_Generalidades/01_Introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Generalidades</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_Generalidades/02_PlanDeArea.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Plan de Área de Ciencias Naturales</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Décimo - Química</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06_Decimo/reactivo_limite.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reactivo límite</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bibliografia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Referencias</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#teoria" id="toc-teoria" class="nav-link active" data-scroll-target="#teoria"><span class="header-section-number">4.1</span> Teoria</a></li>
  <li><a href="#ideas-previas-cuento" id="toc-ideas-previas-cuento" class="nav-link" data-scroll-target="#ideas-previas-cuento"><span class="header-section-number">4.2</span> Ideas Previas - Cuento</a></li>
  <li><a href="#ideas-previas-preguntas" id="toc-ideas-previas-preguntas" class="nav-link" data-scroll-target="#ideas-previas-preguntas"><span class="header-section-number">4.3</span> Ideas Previas - Preguntas</a></li>
  <li><a href="#ideas-previas-contextualizacion" id="toc-ideas-previas-contextualizacion" class="nav-link" data-scroll-target="#ideas-previas-contextualizacion"><span class="header-section-number">4.4</span> Ideas Previas - Contextualizacion</a></li>
  <li><a href="#contextualizacion-metodo-richard-feynman" id="toc-contextualizacion-metodo-richard-feynman" class="nav-link" data-scroll-target="#contextualizacion-metodo-richard-feynman"><span class="header-section-number">4.5</span> Contextualizacion - Metodo Richard Feynman</a></li>
  <li><a href="#contextualizacion-apoyo-cognitivo-y-tdah" id="toc-contextualizacion-apoyo-cognitivo-y-tdah" class="nav-link" data-scroll-target="#contextualizacion-apoyo-cognitivo-y-tdah"><span class="header-section-number">4.6</span> Contextualizacion - Apoyo Cognitivo y TDAH</a></li>
  <li><a href="#contextualizacion-visual" id="toc-contextualizacion-visual" class="nav-link" data-scroll-target="#contextualizacion-visual"><span class="header-section-number">4.7</span> Contextualizacion - Visual</a></li>
  <li><a href="#contextualizacion-dislexia-y-dificultades-lectoras" id="toc-contextualizacion-dislexia-y-dificultades-lectoras" class="nav-link" data-scroll-target="#contextualizacion-dislexia-y-dificultades-lectoras"><span class="header-section-number">4.8</span> Contextualizacion - Dislexia y Dificultades Lectoras</a></li>
  <li><a href="#contextualizacion-autismo-y-pensamiento-concreto" id="toc-contextualizacion-autismo-y-pensamiento-concreto" class="nav-link" data-scroll-target="#contextualizacion-autismo-y-pensamiento-concreto"><span class="header-section-number">4.9</span> Contextualizacion - Autismo y Pensamiento Concreto</a></li>
  <li><a href="#contextualizacion-accesibilidad-sensorial" id="toc-contextualizacion-accesibilidad-sensorial" class="nav-link" data-scroll-target="#contextualizacion-accesibilidad-sensorial"><span class="header-section-number">4.10</span> Contextualizacion - Accesibilidad Sensorial</a></li>
  <li><a href="#contextualizacion-socioemocional-y-psicosocial" id="toc-contextualizacion-socioemocional-y-psicosocial" class="nav-link" data-scroll-target="#contextualizacion-socioemocional-y-psicosocial"><span class="header-section-number">4.11</span> Contextualizacion - Socioemocional y Psicosocial</a></li>
  <li><a href="#ejemplo-guiado-nivel-bajo" id="toc-ejemplo-guiado-nivel-bajo" class="nav-link" data-scroll-target="#ejemplo-guiado-nivel-bajo"><span class="header-section-number">4.12</span> Ejemplo Guiado - Nivel Bajo</a></li>
  <li><a href="#ejemplo-guiado-nivel-medio" id="toc-ejemplo-guiado-nivel-medio" class="nav-link" data-scroll-target="#ejemplo-guiado-nivel-medio"><span class="header-section-number">4.13</span> Ejemplo Guiado - Nivel Medio</a></li>
  <li><a href="#ejemplo-guiado-nivel-alto" id="toc-ejemplo-guiado-nivel-alto" class="nav-link" data-scroll-target="#ejemplo-guiado-nivel-alto"><span class="header-section-number">4.14</span> Ejemplo Guiado - Nivel Alto</a></li>
  <li><a href="#nivel-bajo" id="toc-nivel-bajo" class="nav-link" data-scroll-target="#nivel-bajo"><span class="header-section-number">4.15</span> Nivel Bajo</a></li>
  <li><a href="#nivel-medio" id="toc-nivel-medio" class="nav-link" data-scroll-target="#nivel-medio"><span class="header-section-number">4.16</span> Nivel Medio</a></li>
  <li><a href="#nivel-alto" id="toc-nivel-alto" class="nav-link" data-scroll-target="#nivel-alto"><span class="header-section-number">4.17</span> Nivel Alto</a></li>
  <li><a href="#retos" id="toc-retos" class="nav-link" data-scroll-target="#retos"><span class="header-section-number">4.18</span> Retos</a></li>
  <li><a href="#aplicacion-vida-real" id="toc-aplicacion-vida-real" class="nav-link" data-scroll-target="#aplicacion-vida-real"><span class="header-section-number">4.19</span> Aplicacion - Vida real</a></li>
  <li><a href="#aplicacion-laboratorio" id="toc-aplicacion-laboratorio" class="nav-link" data-scroll-target="#aplicacion-laboratorio"><span class="header-section-number">4.20</span> Aplicacion - Laboratorio</a></li>
  <li><a href="#evaluacion-tipo-icfes" id="toc-evaluacion-tipo-icfes" class="nav-link" data-scroll-target="#evaluacion-tipo-icfes"><span class="header-section-number">4.21</span> Evaluacion - tipo ICFES</a></li>
  <li><a href="#socializacion" id="toc-socializacion" class="nav-link" data-scroll-target="#socializacion"><span class="header-section-number">4.22</span> Socializacion</a></li>
  <li><a href="#socioemocional" id="toc-socioemocional" class="nav-link" data-scroll-target="#socioemocional"><span class="header-section-number">4.23</span> Socioemocional</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/camilotayac/docere/edit/main/06_Decimo/reactivo_limite.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reactivo límite</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="teoria" class="level2 teoria-box-heading" data-number="4.1">
<h2 class="teoria-box-heading anchored" data-number="4.1" data-anchor-id="teoria"><span class="header-section-number">4.1</span> Teoria</h2>
<div class="teoria-box" title="Teoria">
<p>La <strong>estequiometría</strong> es la rama de la química que estudia las relaciones cuantitativas entre reactivos y productos en una reacción química balanceada. Cuando se lleva a cabo una reacción, los reactivos no siempre están presentes en las proporciones exactas que indica la ecuación balanceada. En tales casos, uno de los reactivos se consume completamente antes que los demás, limitando la cantidad de producto que se puede formar. A este reactivo se le denomina <strong>reactivo límite</strong> (o reactivo limitante), mientras que los reactivos que no se consumen totalmente reciben el nombre de <strong>reactivos en exceso</strong> <span class="citation" data-cites="chang2017quimica">(<a href="../bibliografia.html#ref-chang2017quimica" role="doc-biblioref">Chang and Goldsby 2017</a>)</span>.</p>
<p>Para identificar el reactivo límite se siguen cuatro pasos: (1) escribir y balancear la ecuación química; (2) convertir las masas de los reactivos a moles usando las masas molares; (3) dividir los moles de cada reactivo entre su coeficiente estequiométrico en la ecuación balanceada; y (4) el reactivo con el menor cociente es el reactivo límite. Una vez identificado, se usan sus moles para calcular la cantidad máxima de producto posible, denominada <strong>rendimiento teórico</strong>.</p>
<p><strong>Fórmula (1):</strong></p>
<p><span class="math display">\[ n = \frac{m}{M} \tag{1} \]</span></p>
<p>Donde <span class="math inline">\(n\)</span> = cantidad de sustancia (mol), <span class="math inline">\(m\)</span> = masa del reactivo (g), <span class="math inline">\(M\)</span> = masa molar (g/mol).</p>
<p>El <strong>porcentaje de rendimiento</strong> relaciona el rendimiento real (obtenido experimentalmente) con el rendimiento teórico:</p>
<p><strong>Fórmula (2):</strong></p>
<p><span class="math display">\[ \% \text{ rendimiento} = \frac{\text{rendimiento real}}{\text{rendimiento teórico}} \times 100 \tag{2} \]</span></p>
<p>Donde rendimiento real = masa de producto obtenida experimentalmente (g), rendimiento teórico = masa máxima calculada a partir del reactivo límite (g).</p>
<p><span class="citation" data-cites="brown2022chemistry">(<a href="../bibliografia.html#ref-brown2022chemistry" role="doc-biblioref">Brown et al. 2022</a>)</span></p>
</div>
</section>
<section id="ideas-previas-cuento" class="level2 ideas-previas-box-heading" data-number="4.2">
<h2 class="ideas-previas-box-heading anchored" data-number="4.2" data-anchor-id="ideas-previas-cuento"><span class="header-section-number">4.2</span> Ideas Previas - Cuento</h2>
<div class="ideas-previas-box" title="Ideas Previas - Cuento">
<p>Imagina que estás armando emparedados para una fiesta y tienes 12 rebanadas de pan y 8 tajadas de queso. Cada emparedado necesita dos rebanadas de pan y una tajada de queso. Empiezas a armar y, después del octavo emparedado, te das cuenta de que ya no queda queso, pero todavía te sobran rebanadas de pan. El queso determinó cuántos emparedados pudiste hacer.</p>
<ul>
<li><p><strong>¿Qué crees que pasaría si, en lugar de 8 tajadas de queso, hubieras tenido 15? ¿Habrían cambiado los emparedados que lograste armar?</strong></p>
<p></p>
<p></p></li>
<li><p><strong>¿Puedes imaginar una situación similar en tu casa donde un ingrediente se acabe antes que otro cuando cocinas o preparas algo?</strong></p>
<p></p>
<p></p></li>
<li><p><strong>¿Crees que el ingrediente que “sobra” podría usarse para algo más después de terminar la receta original?</strong></p>
<p></p>
<p></p></li>
<li><p><strong>¿Por qué será importante identificar cuál ingrediente se acaba primero cuando trabajas con cantidades limitadas?</strong></p>
<p></p>
<p></p></li>
</ul>
</div>
</section>
<section id="ideas-previas-preguntas" class="level2 ideas-previas-box-heading" data-number="4.3">
<h2 class="ideas-previas-box-heading anchored" data-number="4.3" data-anchor-id="ideas-previas-preguntas"><span class="header-section-number">4.3</span> Ideas Previas - Preguntas</h2>
<div class="ideas-previas-box" title="Ideas Previas - Preguntas">
<ul>
<li><p><strong>¿Qué crees que significa que algo sea “limitante” en un proceso cotidiano?</strong></p>
<p></p>
<p></p></li>
<li><p><strong>¿Has tenido que racionar algún material en un proyecto porque sabías que no alcanzaba para todos?</strong></p>
<p></p>
<p></p></li>
<li><p><strong>Si tuvieras que explicarle a un compañero qué es un reactivo límite usando solo objetos del salón, ¿qué usarías y cómo lo harías?</strong></p>
<p></p>
<p></p></li>
<li><p><strong>¿Por qué piensas que en química es importante saber cuál reactivo se acaba primero?</strong></p>
<p></p>
<p></p></li>
</ul>
</div>
</section>
<section id="ideas-previas-contextualizacion" class="level2 ideas-previas-box-heading" data-number="4.4">
<h2 class="ideas-previas-box-heading anchored" data-number="4.4" data-anchor-id="ideas-previas-contextualizacion"><span class="header-section-number">4.4</span> Ideas Previas - Contextualizacion</h2>
<div class="ideas-previas-box" title="Ideas Previas - Contextualizacion">
<p>En el municipio de Nemocón (Cundinamarca), las minas de sal han operado durante siglos. Los mineros saben que, para extraer una tonelada de sal, necesitan cierta cantidad de agua y cierta cantidad de energía térmica. Si un día solo tienen suficiente carbón para calentar el agua durante la mitad del tiempo necesario, la producción de ese día estará limitada por el combustible, no por el agua disponible. De manera similar, en una reacción química uno de los reactivos se agota antes y determina cuánto producto se puede obtener.</p>
</div>
</section>
<section id="contextualizacion-metodo-richard-feynman" class="level2 contexto-box-heading" data-number="4.5">
<h2 class="contexto-box-heading anchored" data-number="4.5" data-anchor-id="contextualizacion-metodo-richard-feynman"><span class="header-section-number">4.5</span> Contextualizacion - Metodo Richard Feynman</h2>
<div class="contexto-box" title="Contextualizacion - Metodo Richard Feynman">
<p>¿Alguna vez has armado un mueble de kit y te has dado cuenta de que te faltan tornillos? Revisas la bolsa de piezas, cuentas los tornillos que tienes, y luego miras el instructivo: cada panel frontal necesita dos tornillos. Resulta que tienes 10 paneles pero solo 12 tornillos. Aunque tengas los 10 paneles listos, solo podrás fijar 6 de ellos porque los tornillos se acaban primero. Pues bien, en química ocurre exactamente lo mismo: los tornillos son uno de los <strong>reactivos</strong>, los paneles son el otro, y el <strong>reactivo límite</strong> son esos tornillos que determinan cuántos muebles completos puedes armar. Pero cuidado: en química no siempre es tan sencillo como contar piezas, porque los reactivos se combinan en proporciones fijas según la ecuación balanceada, y hay que usar moles (no unidades individuales) para hacer los cálculos correctos.</p>
</div>
</section>
<section id="contextualizacion-apoyo-cognitivo-y-tdah" class="level2 caracterizados-box-heading" data-number="4.6">
<h2 class="caracterizados-box-heading anchored" data-number="4.6" data-anchor-id="contextualizacion-apoyo-cognitivo-y-tdah"><span class="header-section-number">4.6</span> Contextualizacion - Apoyo Cognitivo y TDAH</h2>
<div class="caracterizados-box" title="Contextualizacion - Apoyo Cognitivo y TDAH">
<p>Para identificar el reactivo límite sigue estos pasos en orden:</p>
<ol type="1">
<li>Escribe y balancea la ecuación química.</li>
<li>Convierte las masas a moles. <strong>Fórmula:</strong> <span class="math inline">\(n = \frac{m}{M}\)</span> (<span class="math inline">\(n\)</span> = moles, <span class="math inline">\(m\)</span> = masa en gramos, <span class="math inline">\(M\)</span> = masa molar en g/mol)</li>
<li>Divide los moles entre su coeficiente.</li>
<li>El cociente más pequeño es el <strong>reactivo límite</strong>.</li>
<li>Usa sus moles para calcular el producto.</li>
</ol>
<p><strong>Ejemplo:</strong> En la reacción <span class="math inline">\(Fe + S \rightarrow FeS\)</span> se tienen 55.85 g de Fe y 48.09 g de S. Masas molares: Fe = 55.85 g/mol, S = 32.06 g/mol.</p>
<p><strong>Paso 1:</strong> Convertir a moles. Fe: 55.85 ÷ 55.85 = 1.00 mol. S: 48.09 ÷ 32.06 = 1.50 mol.</p>
<p><strong>Paso 2:</strong> Dividir entre coeficiente. Fe: 1.00 ÷ 1 = 1.00. S: 1.50 ÷ 1 = 1.50.</p>
<p><strong>Paso 3:</strong> Comparar. 1.00 &lt; 1.50. El <strong>Fe</strong> es el reactivo límite.</p>
<p><strong>Paso 4:</strong> Calcular producto. 1.00 mol Fe × (1 mol FeS / 1 mol Fe) = 1.00 mol FeS = 87.91 g.</p>
<p><strong>Ejercicios:</strong></p>
<ol type="1">
<li><p>En <span class="math inline">\(2Al + 3S \rightarrow Al_2S_3\)</span> se tienen 26.98 g de Al y 64.12 g de S (masas molares: Al = 26.98 g/mol, S = 32.06 g/mol). Sigue los 4 pasos para hallar el reactivo límite y los gramos de <span class="math inline">\(Al_2S_3\)</span>.</p>
<p></p>
<p></p>
<p></p></li>
<li><p>En <span class="math inline">\(2Mg + O_2 \rightarrow 2MgO\)</span> se tienen 24.30 g de Mg y 32.00 g de <span class="math inline">\(O_2\)</span> (masas molares: Mg = 24.30 g/mol, <span class="math inline">\(O_2\)</span> = 32.00 g/mol). ¿Cuál es el reactivo límite y qué masa de MgO se produce?</p>
<p></p>
<p></p>
<p></p></li>
</ol>
</div>
</section>
<section id="contextualizacion-visual" class="level2 caracterizados-box-heading" data-number="4.7">
<h2 class="caracterizados-box-heading anchored" data-number="4.7" data-anchor-id="contextualizacion-visual"><span class="header-section-number">4.7</span> Contextualizacion - Visual</h2>
<div class="caracterizados-box" title="Contextualizacion - Visual">
<p>Reacción: <strong>Fe + S → FeS</strong> (balanceada 1:1)</p>
<p>Datos de entrada:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Reactivo</th>
<th>Masa (g)</th>
<th>M (g/mol)</th>
<th>Moles (n)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fe <strong>(azul)</strong></td>
<td>55.85</td>
<td>55.85</td>
<td>55.85 ÷ 55.85 = <strong>1.00 mol</strong></td>
</tr>
<tr class="even">
<td>S <strong>(rojo)</strong></td>
<td>48.09</td>
<td>32.06</td>
<td>48.09 ÷ 32.06 = <strong>1.50 mol</strong></td>
</tr>
</tbody>
</table>
<p><strong>Moles de Fe = 1.00 (azul)</strong> — <strong>Moles de S = 1.50 (rojo)</strong></p>
<p>Dividir entre coeficiente (ambos = 1):</p>
<pre><code>Fe (azul): 1.00 ÷ 1 = 1.00
S  (rojo): 1.50 ÷ 1 = 1.50
Menor cociente → Fe es RL (verde)</code></pre>
<p><strong>Ejemplo:</strong> Del diagrama anterior, Fe es el reactivo límite <strong>(verde)</strong>. Calcular producto: 1.00 mol × (1/1) × 87.91 g/mol = <strong>87.91 g FeS (verde)</strong>.</p>
<p><strong>Ejercicios:</strong></p>
<ol type="1">
<li><p>Completa la tabla para <span class="math inline">\(2Al + 3S \rightarrow Al_2S_3\)</span> con 26.98 g Al y 64.12 g S. ¿Qué reactivo está <strong>(azul)</strong> y cuál <strong>(rojo)</strong>? ¿Cuál es <strong>(verde)</strong> el RL?</p>
<p></p>
<p></p></li>
<li><p>Dibuja el diagrama de flujo para <span class="math inline">\(2Mg + O_2 \rightarrow 2MgO\)</span> con 24.30 g Mg y 32.00 g <span class="math inline">\(O_2\)</span>. Incluye los cocientes y señala el RL. Usa <strong>(azul)</strong>, <strong>(rojo)</strong> y <strong>(verde)</strong>.</p>
<p></p>
<p></p></li>
</ol>
</div>
</section>
<section id="contextualizacion-dislexia-y-dificultades-lectoras" class="level2 caracterizados-box-heading" data-number="4.8">
<h2 class="caracterizados-box-heading anchored" data-number="4.8" data-anchor-id="contextualizacion-dislexia-y-dificultades-lectoras"><span class="header-section-number">4.8</span> Contextualizacion - Dislexia y Dificultades Lectoras</h2>
<div class="caracterizados-box" title="Contextualizacion - Dislexia y Dificultades Lectoras">
<p>Una ecuación química es una receta. Los reactivos son los ingredientes. El producto es el resultado. La ecuación balanceada dice cuánto necesitas de cada reactivo. El reactivo límite es el ingrediente que se acaba primero.</p>
<p><strong>Ejemplo:</strong> La reacción es <span class="math inline">\(Fe + S \rightarrow FeS\)</span>. Tienes 55.85 g de Fe y 48.09 g de S.</p>
<ol type="1">
<li><strong>Convierte a moles.</strong> 55.85 g Fe → 1.00 mol. 48.09 g S → 1.50 mol.</li>
<li><strong>Divide por el coeficiente.</strong> Fe: 1.00 ÷ 1 = 1.00. S: 1.50 ÷ 1 = 1.50.</li>
<li><strong>Compara.</strong> 1.00 &lt; 1.50. El Fe se acaba primero.</li>
</ol>
<p><strong>Resultado:</strong> El Fe es el reactivo límite. Se forman 87.91 g de FeS.</p>
<p><strong>Ejercicios:</strong></p>
<ol type="1">
<li><p>En <span class="math inline">\(2Al + 3S \rightarrow Al_2S_3\)</span> tienes 26.98 g de Al y 64.12 g de S. Sigue los 3 pasos para hallar el reactivo límite.</p>
<p></p>
<p></p>
<p></p></li>
<li><p>En <span class="math inline">\(2Mg + O_2 \rightarrow 2MgO\)</span> tienes 24.30 g de Mg y 32.00 g de <span class="math inline">\(O_2\)</span>. ¿Cuál reactivo se acaba primero? Calcula los gramos de MgO.</p>
<p></p>
<p></p>
<p></p></li>
</ol>
</div>
</section>
<section id="contextualizacion-autismo-y-pensamiento-concreto" class="level2 caracterizados-box-heading" data-number="4.9">
<h2 class="caracterizados-box-heading anchored" data-number="4.9" data-anchor-id="contextualizacion-autismo-y-pensamiento-concreto"><span class="header-section-number">4.9</span> Contextualizacion - Autismo y Pensamiento Concreto</h2>
<div class="caracterizados-box" title="Contextualizacion - Autismo y Pensamiento Concreto">
<p>Regla fija: los reactivos se combinan en una proporción fija de moles. El reactivo con el cociente (moles ÷ coeficiente) más pequeño se agota primero. Ese es el reactivo límite.</p>
<p><strong>Ejemplo:</strong> Reacción <span class="math inline">\(Fe + S \rightarrow FeS\)</span>. Coeficientes: ambos 1. Datos: 55.85 g Fe y 48.09 g S.</p>
<ol type="1">
<li>Moles de Fe = 55.85 ÷ 55.85 = 1.00 mol. Moles de S = 48.09 ÷ 32.06 = 1.50 mol.</li>
<li>Cociente de Fe = 1.00 ÷ 1 = 1.00.</li>
<li>Cociente de S = 1.50 ÷ 1 = 1.50.</li>
<li>Aplicar la regla fija. 1.00 &lt; 1.50. El Fe tiene el cociente más pequeño. El Fe es el reactivo límite.</li>
<li>Producto = 1.00 mol Fe × (1 mol FeS / 1 mol Fe) × 87.91 g/mol = 87.91 g FeS.</li>
</ol>
<p><strong>Ejercicios:</strong></p>
<ol type="1">
<li><p>Aplica la regla fija a <span class="math inline">\(2Al + 3S \rightarrow Al_2S_3\)</span> con 26.98 g Al y 64.12 g S. ¿Cuál es el reactivo límite?</p>
<p></p>
<p></p>
<p></p></li>
<li><p>Aplica la regla fija a <span class="math inline">\(2Mg + O_2 \rightarrow 2MgO\)</span> con 24.30 g Mg y 32.00 g <span class="math inline">\(O_2\)</span>. ¿Cuántos gramos de MgO se producen?</p>
<p></p>
<p></p>
<p></p></li>
</ol>
</div>
</section>
<section id="contextualizacion-accesibilidad-sensorial" class="level2 caracterizados-box-heading" data-number="4.10">
<h2 class="caracterizados-box-heading anchored" data-number="4.10" data-anchor-id="contextualizacion-accesibilidad-sensorial"><span class="header-section-number">4.10</span> Contextualizacion - Accesibilidad Sensorial</h2>
<div class="caracterizados-box" title="Contextualizacion - Accesibilidad Sensorial">
<p>[Formato accesible: texto plano. Funciona con lectores de pantalla.]</p>
<p>[Ecuación química: Fe (hierro) más S (azufre) produce FeS (sulfuro de hierro). Los coeficientes son ambos 1, lo que significa que un mol de Fe reacciona con exactamente un mol de S.]</p>
<p><strong>Ejemplo:</strong> [Se tienen 55.85 gramos de Fe (hierro) y 48.09 gramos de S (azufre). La masa molar del Fe (hierro) es 55.85 gramos por mol. La masa molar del S (azufre) es 32.06 gramos por mol.]</p>
<ol type="1">
<li>[Convertir masa a moles. Para Fe (hierro): 55.85 dividido 55.85 es igual a 1.00 mol. Para S (azufre): 48.09 dividido 32.06 es igual a 1.50 moles.]</li>
<li>[Dividir moles entre coeficiente. Fe (hierro): 1.00 dividido 1 es 1.00. S (azufre): 1.50 dividido 1 es 1.50.]</li>
</ol>
<p><strong>Resultado:</strong> [El cociente de Fe (hierro) es menor que el de S (azufre). Fe (hierro) es el reactivo límite. Se producen 87.91 gramos de FeS (sulfuro de hierro).]</p>
<p><strong>Ejercicios:</strong></p>
<ol type="1">
<li><p>[Reacción: 2Al (aluminio) más 3S (azufre) produce Al2S3 (sulfuro de aluminio). Datos: 26.98 gramos de Al (aluminio) y 64.12 gramos de S (azufre). Masa molar del Al (aluminio): 26.98 g/mol. Masa molar del S (azufre): 32.06 g/mol. Convierte a moles, divide entre coeficientes e identifica el reactivo límite.]</p>
<p></p>
<p></p>
<p></p></li>
<li><p>[Reacción: 2Mg (magnesio) más O2 (oxígeno molecular) produce 2MgO (óxido de magnesio). Datos: 24.30 gramos de Mg (magnesio) y 32.00 gramos de O2 (oxígeno molecular). Masa molar del Mg (magnesio): 24.30 g/mol. Masa molar del O2 (oxígeno molecular): 32.00 g/mol. Determina cuál es el reactivo límite y la masa de MgO (óxido de magnesio) producida.]</p>
<p></p>
<p></p>
<p></p></li>
</ol>
</div>
</section>
<section id="contextualizacion-socioemocional-y-psicosocial" class="level2 caracterizados-box-heading" data-number="4.11">
<h2 class="caracterizados-box-heading anchored" data-number="4.11" data-anchor-id="contextualizacion-socioemocional-y-psicosocial"><span class="header-section-number">4.11</span> Contextualizacion - Socioemocional y Psicosocial</h2>
<div class="caracterizados-box" title="Contextualizacion - Socioemocional y Psicosocial">
<p>Sabemos que los cálculos con muchos pasos pueden sentirse difíciles al principio, pero no te preocupes: vamos a hacerlo juntos, paso a paso. Cada paso que completes te acerca a dominar el concepto. Tú puedes hacerlo.</p>
<p><strong>Ejemplo:</strong> Observa esta reacción: <span class="math inline">\(Fe + S \rightarrow FeS\)</span>. Vamos a ver si el Fe o el S se acaba primero. Es más sencillo de lo que parece.</p>
<ol type="1">
<li><strong>Convertimos las masas a moles.</strong> 55.85 g de Fe son 1.00 mol. 48.09 g de S son 1.50 moles. Bien, ya dimos el primer paso.</li>
<li><strong>Dividimos cada cantidad entre su coeficiente</strong> (los dos son 1, así que no cambia). Fe: 1.00. S: 1.50.</li>
<li><strong>Comparamos:</strong> 1.00 &lt; 1.50. El que tiene el número más pequeño es el reactivo límite. ¡El Fe se acaba primero! Es como cuando en un juego el recurso más escaso determina hasta dónde puedes llegar. Tú ya identificaste ese recurso.</li>
</ol>
<p><strong>Resultado:</strong> El Fe produce 1.00 mol de FeS, que son 87.91 gramos. ¡Lo lograste!</p>
<p><strong>Ejercicios:</strong></p>
<p>¡Inténtalo! Ya viste cómo se hace. Vas a descubrir que puedes resolverlo solo.</p>
<ol type="1">
<li><p>En la reacción <span class="math inline">\(2Al + 3S \rightarrow Al_2S_3\)</span>, tienes 26.98 g de Al y 64.12 g de S. Sigue los mismos pasos del ejemplo. ¿Cuál es el reactivo límite?</p>
<p></p>
<p></p>
<p></p></li>
<li><p>En <span class="math inline">\(2Mg + O_2 \rightarrow 2MgO\)</span>, con 24.30 g de Mg y 32.00 g de <span class="math inline">\(O_2\)</span>, ¿qué masa de MgO puedes obtener? Confía en tu proceso, paso a paso.</p>
<p></p>
<p></p>
<p></p></li>
</ol>
</div>
</section>
<section id="ejemplo-guiado-nivel-bajo" class="level2 ejemplo-box-heading" data-number="4.12">
<h2 class="ejemplo-box-heading anchored" data-number="4.12" data-anchor-id="ejemplo-guiado-nivel-bajo"><span class="header-section-number">4.12</span> Ejemplo Guiado - Nivel Bajo</h2>
<div class="ejemplo-box" title="Ejemplo Guiado - Nivel Bajo">
<p><strong>Enunciado:</strong> La síntesis del metanol (<span class="math inline">\(CH_3OH\)</span>) a partir de monóxido de carbono e hidrógeno sigue la reacción:</p>
<p><span class="math display">\[CO(g) + 2H_2(g) \rightarrow CH_3OH(g)\]</span></p>
<p>Si se tienen 4 moles de CO y 6 moles de <span class="math inline">\(H_2\)</span>, ¿cuál es el reactivo límite y cuántos moles de <span class="math inline">\(CH_3OH\)</span> se pueden producir?</p>
<p><strong>Justificacion Teorica:</strong> El reactivo límite se identifica dividiendo los moles disponibles de cada reactivo entre su coeficiente estequiométrico. El reactivo con el menor cociente es el límite.</p>
<p><strong>Ejecucion:</strong></p>
<p><strong>Paso 1: Dividir moles de CO entre su coeficiente</strong> <span class="math inline">\(4 \text{ mol CO} \div 1 = 4\)</span> &lt;- (el coeficiente del CO es 1)</p>
<p><strong>Paso 2: Dividir moles de H<span class="math inline">\(_2\)</span> entre su coeficiente</strong> <span class="math inline">\(6 \text{ mol H}_2 \div 2 = 3\)</span> &lt;- (el coeficiente del H<span class="math inline">\(_2\)</span> es 2)</p>
<p><strong>Paso 3: Comparar cocientes</strong> <span class="math inline">\(3 &lt; 4\)</span>, por lo tanto el H<span class="math inline">\(_2\)</span> es el <strong>reactivo límite</strong>.</p>
<p><strong>Paso 4: Calcular moles de producto usando el reactivo límite</strong> <span class="math inline">\(6 \text{ mol H}_2 \times \frac{1 \text{ mol CH}_3\text{OH}}{2 \text{ mol H}_2} = 3 \text{ mol CH}_3\text{OH}\)</span></p>
<p><strong>Resultado:</strong> El reactivo límite es el <span class="math inline">\(H_2\)</span> y se producen 3 moles de <span class="math inline">\(CH_3OH\)</span> <span class="citation" data-cites="chang2017quimica">(<a href="../bibliografia.html#ref-chang2017quimica" role="doc-biblioref">Chang and Goldsby 2017</a>)</span>.</p>
</div>
</section>
<section id="ejemplo-guiado-nivel-medio" class="level2 ejemplo-box-heading" data-number="4.13">
<h2 class="ejemplo-box-heading anchored" data-number="4.13" data-anchor-id="ejemplo-guiado-nivel-medio"><span class="header-section-number">4.13</span> Ejemplo Guiado - Nivel Medio</h2>
<div class="ejemplo-box" title="Ejemplo Guiado - Nivel Medio">
<p><strong>Enunciado:</strong> La reacción entre el óxido nítrico y el oxígeno produce dióxido de nitrógeno:</p>
<p><span class="math display">\[2NO(g) + O_2(g) \rightarrow 2NO_2(g)\]</span></p>
<p>Si se hacen reaccionar 30.0 g de NO con 20.0 g de <span class="math inline">\(O_2\)</span>, determine el reactivo límite y la masa de <span class="math inline">\(NO_2\)</span> producida. Masas molares: NO = 30.01 g/mol, <span class="math inline">\(O_2\)</span> = 32.00 g/mol, <span class="math inline">\(NO_2\)</span> = 46.01 g/mol.</p>
<p><strong>Justificacion Teorica:</strong> Primero se convierten las masas a moles, luego se dividen entre los coeficientes para identificar el reactivo límite. Finalmente se usa la relación molar para calcular la masa de producto.</p>
<p><strong>Ejecucion:</strong></p>
<p><strong>Paso 1: Convertir masa de NO a moles</strong> <span class="math inline">\(n_{NO} = \frac{30.0 \text{ g}}{30.01 \text{ g/mol}} = 1.00 \text{ mol NO}\)</span></p>
<p><strong>Paso 2: Convertir masa de O<span class="math inline">\(_2\)</span> a moles</strong> <span class="math inline">\(n_{O_2} = \frac{20.0 \text{ g}}{32.00 \text{ g/mol}} = 0.625 \text{ mol O}_2\)</span></p>
<p><strong>Paso 3: Dividir cada uno entre su coeficiente</strong> NO: <span class="math inline">\(1.00 \div 2 = 0.500\)</span> &lt;- (coeficiente 2) O<span class="math inline">\(_2\)</span>: <span class="math inline">\(0.625 \div 1 = 0.625\)</span> &lt;- (coeficiente 1)</p>
<p><strong>Paso 4: Identificar reactivo límite</strong> <span class="math inline">\(0.500 &lt; 0.625\)</span>, el <strong>NO</strong> es el reactivo límite.</p>
<p><strong>Paso 5: Calcular masa de NO<span class="math inline">\(_2\)</span> producida</strong> <span class="math inline">\(1.00 \text{ mol NO} \times \frac{2 \text{ mol NO}_2}{2 \text{ mol NO}} \times \frac{46.01 \text{ g}}{\text{mol}} = 46.01 \text{ g NO}_2\)</span></p>
<p><strong>Resultado:</strong> El reactivo límite es el NO y se producen 46.01 g de <span class="math inline">\(NO_2\)</span> <span class="citation" data-cites="brown2022chemistry">(<a href="../bibliografia.html#ref-brown2022chemistry" role="doc-biblioref">Brown et al. 2022</a>)</span>.</p>
</div>
</section>
<section id="ejemplo-guiado-nivel-alto" class="level2 ejemplo-box-heading" data-number="4.14">
<h2 class="ejemplo-box-heading anchored" data-number="4.14" data-anchor-id="ejemplo-guiado-nivel-alto"><span class="header-section-number">4.14</span> Ejemplo Guiado - Nivel Alto</h2>
<div class="ejemplo-box" title="Ejemplo Guiado - Nivel Alto">
<p><strong>Enunciado:</strong> La urea <span class="math inline">\([(NH_2)_2CO]\)</span> se prepara a partir de amoníaco y dióxido de carbono:</p>
<p><span class="math display">\[2NH_3(g) + CO_2(g) \rightarrow (NH_2)_2CO(ac) + H_2O(l)\]</span></p>
<p>En un proceso se hacen reaccionar 637.2 g de <span class="math inline">\(NH_3\)</span> con 1142 g de <span class="math inline">\(CO_2\)</span>. Determine: (a) el reactivo límite, (b) la masa de urea que se formará, (c) la masa del reactivo en exceso que queda sin reaccionar. Masas molares: <span class="math inline">\(NH_3\)</span> = 17.03 g/mol, <span class="math inline">\(CO_2\)</span> = 44.01 g/mol, <span class="math inline">\((NH_2)_2CO\)</span> = 60.06 g/mol.</p>
<p><strong>Justificacion Teorica:</strong> Se requieren tres etapas: identificar el reactivo límite comparando los moles ajustados por coeficiente; calcular la masa de producto usando el reactivo límite; y determinar cuánto del otro reactivo se consumió para hallar el sobrante.</p>
<p><strong>Ejecucion:</strong></p>
<p><strong>Paso 1: Convertir masas a moles</strong> <span class="math inline">\(n_{NH_3} = 637.2 \text{ g} \div 17.03 \text{ g/mol} = 37.42 \text{ mol}\)</span> <span class="math inline">\(n_{CO_2} = 1142 \text{ g} \div 44.01 \text{ g/mol} = 25.95 \text{ mol}\)</span></p>
<p><strong>Paso 2: Dividir entre coeficientes</strong> <span class="math inline">\(NH_3\)</span>: <span class="math inline">\(37.42 \div 2 = 18.71\)</span> <span class="math inline">\(CO_2\)</span>: <span class="math inline">\(25.95 \div 1 = 25.95\)</span></p>
<p><strong>Paso 3: Identificar reactivo límite</strong> <span class="math inline">\(18.71 &lt; 25.95\)</span>, el <strong><span class="math inline">\(NH_3\)</span></strong> es el reactivo límite.</p>
<p><strong>Paso 4: Calcular masa de urea producida</strong> <span class="math inline">\(37.42 \text{ mol NH}_3 \times \frac{1 \text{ mol urea}}{2 \text{ mol NH}_3} \times \frac{60.06 \text{ g}}{\text{mol}} = 1123.7 \text{ g urea}\)</span></p>
<p><strong>Paso 5: Calcular moles de CO<span class="math inline">\(_2\)</span> consumidos</strong> <span class="math inline">\(37.42 \text{ mol NH}_3 \times \frac{1 \text{ mol CO}_2}{2 \text{ mol NH}_3} = 18.71 \text{ mol CO}_2\)</span></p>
<p><strong>Paso 6: Calcular masa de CO<span class="math inline">\(_2\)</span> sobrante</strong> <span class="math inline">\(25.95 - 18.71 = 7.24 \text{ mol CO}_2\)</span> sin reaccionar <span class="math inline">\(7.24 \text{ mol} \times 44.01 \text{ g/mol} = 318.6 \text{ g CO}_2\)</span></p>
<p><strong>Resultado:</strong> (a) El reactivo límite es el <span class="math inline">\(NH_3\)</span>. (b) Se producen 1124 g de urea. (c) Quedan 319 g de <span class="math inline">\(CO_2\)</span> sin reaccionar. <span class="citation" data-cites="chang2017quimica">(<a href="../bibliografia.html#ref-chang2017quimica" role="doc-biblioref">Chang and Goldsby 2017</a>)</span></p>
</div>
</section>
<section id="nivel-bajo" class="level2 ejercicios-box-heading" data-number="4.15">
<h2 class="ejercicios-box-heading anchored" data-number="4.15" data-anchor-id="nivel-bajo"><span class="header-section-number">4.15</span> Nivel Bajo</h2>
<div class="ejercicios-box" title="Nivel Bajo">
<ul>
<li><p>Completar: En la reacción <span class="math inline">\(2H_2 + O_2 \rightarrow 2H_2O\)</span>, si se tienen 3 moles de <span class="math inline">\(H_2\)</span> y 2 moles de <span class="math inline">\(O_2\)</span>, el reactivo límite es el porque su cociente de moles dividido entre coeficiente es , mientras que el del otro reactivo es .</p></li>
<li><p>V/F: El reactivo en exceso es aquel que se consume completamente durante la reacción. ()</p></li>
<li><p>Identificación: En la ecuación <span class="math inline">\(N_2 + 3H_2 \rightarrow 2NH_3\)</span>, indica cuál es el reactivo límite si se tienen 2 moles de <span class="math inline">\(N_2\)</span> y 5 moles de <span class="math inline">\(H_2\)</span>.</p>
<p></p>
<p></p></li>
</ul>
</div>
</section>
<section id="nivel-medio" class="level2 ejercicios-box-heading" data-number="4.16">
<h2 class="ejercicios-box-heading anchored" data-number="4.16" data-anchor-id="nivel-medio"><span class="header-section-number">4.16</span> Nivel Medio</h2>
<div class="ejercicios-box" title="Nivel Medio">
<ul>
<li><p>Respuesta corta: Se hacen reaccionar 10.0 g de <span class="math inline">\(Zn\)</span> (masa molar 65.38 g/mol) con 5.0 g de <span class="math inline">\(HCl\)</span> (masa molar 36.46 g/mol) según <span class="math inline">\(Zn + 2HCl \rightarrow ZnCl_2 + H_2\)</span>. ¿Cuál es el reactivo límite y cuántos gramos de <span class="math inline">\(ZnCl_2\)</span> se producen?</p>
<p></p>
<p></p>
<p></p></li>
<li><p>Aplicación simple: En la reacción <span class="math inline">\(2Al + 3Cl_2 \rightarrow 2AlCl_3\)</span>, si se tienen 54.0 g de Al y 106.5 g de <span class="math inline">\(Cl_2\)</span>, ¿cuántos gramos de <span class="math inline">\(AlCl_3\)</span> se pueden obtener?</p>
<p></p>
<p></p>
<p></p></li>
<li><p>Clasificación: Dados los siguientes pares de reactivos, identifica en cada caso cuál sería el reactivo límite sin hacer cálculos detallados, solo observando las proporciones: (a) 1 mol <span class="math inline">\(CH_4\)</span> + 3 mol <span class="math inline">\(O_2\)</span> en <span class="math inline">\(CH_4 + 2O_2 \rightarrow CO_2 + 2H_2O\)</span>; (b) 2 mol <span class="math inline">\(Fe\)</span> + 2 mol <span class="math inline">\(O_2\)</span> en <span class="math inline">\(4Fe + 3O_2 \rightarrow 2Fe_2O_3\)</span>.</p>
<p></p>
<p></p></li>
</ul>
</div>
</section>
<section id="nivel-alto" class="level2 ejercicios-box-heading" data-number="4.17">
<h2 class="ejercicios-box-heading anchored" data-number="4.17" data-anchor-id="nivel-alto"><span class="header-section-number">4.17</span> Nivel Alto</h2>
<div class="ejercicios-box" title="Nivel Alto">
<ul>
<li><p>Problema abierto: El etileno (<span class="math inline">\(C_2H_4\)</span>) se puede preparar calentando hexano (<span class="math inline">\(C_6H_{14}\)</span>): <span class="math inline">\(C_6H_{14} \rightarrow C_2H_4 + C_4H_{10} + CH_4\)</span> (sin balancear). Si se calientan 86.0 g de hexano y se obtienen 28.0 g de etileno, calcula el rendimiento porcentual de la reacción. Sugerencia: primero balancea la ecuación.</p>
<p></p>
<p></p>
<p></p></li>
<li><p>Análisis de errores: Un estudiante afirma que en la reacción <span class="math inline">\(2Mg + O_2 \rightarrow 2MgO\)</span>, si se tienen 48.6 g de Mg y 32.0 g de <span class="math inline">\(O_2\)</span>, el reactivo límite es el <span class="math inline">\(O_2\)</span> porque hay menos masa de oxígeno. Explica por qué esta conclusión es incorrecta y determina la respuesta correcta.</p>
<p></p>
<p></p>
<p></p></li>
</ul>
</div>
</section>
<section id="retos" class="level2 retos-box-heading" data-number="4.18">
<h2 class="retos-box-heading anchored" data-number="4.18" data-anchor-id="retos"><span class="header-section-number">4.18</span> Retos</h2>
<div class="retos-box" title="Retos">
<p>El concepto de reactivo límite se aplica en la industria farmacéutica para maximizar la producción de medicamentos usando el principio del reactivo más costoso como límite. Para este reto:</p>
<ul>
<li>Diseña un cartel informativo que explique los cuatro pasos para determinar el reactivo límite usando como ejemplo una reacción de tu elección. Incluye los cálculos paso a paso.</li>
<li>Construye un modelo físico con materiales reciclables (tapas, fichas, cuentas) que represente los moles de cada reactivo antes y después de la reacción, mostrando claramente cuál es el reactivo límite y cuál está en exceso.</li>
<li>Prepara una breve exposición (máximo 3 minutos) explicando por qué es importante identificar el reactivo límite en procesos industriales como la producción de fertilizantes o medicamentos.</li>
</ul>
</div>
</section>
<section id="aplicacion-vida-real" class="level2 aplicacion-box-heading" data-number="4.19">
<h2 class="aplicacion-box-heading anchored" data-number="4.19" data-anchor-id="aplicacion-vida-real"><span class="header-section-number">4.19</span> Aplicacion - Vida real</h2>
<div class="aplicacion-box" title="Aplicacion - Vida real">
<p>En la producción industrial de ácido sulfúrico (<span class="math inline">\(H_2SO_4\)</span>) en plantas como la de Cartagena (Colombia), el azufre se quema para formar <span class="math inline">\(SO_2\)</span>, que luego se oxida a <span class="math inline">\(SO_3\)</span> y finalmente se hidrata. Los ingenieros controlan cuidadosamente las cantidades de reactivos para garantizar que el azufre (el reactivo más costoso y menos abundante) se consuma por completo, mientras que el oxígeno del aire se suministra en exceso. Así se maximiza el rendimiento económico del proceso. La próxima vez que veas una batería de carro o un producto de limpieza, recuerda que el ácido sulfúrico que contienen se fabricó aplicando el concepto de reactivo límite para optimizar su producción.</p>
</div>
</section>
<section id="aplicacion-laboratorio" class="level2 aplicacion-box-heading" data-number="4.20">
<h2 class="aplicacion-box-heading anchored" data-number="4.20" data-anchor-id="aplicacion-laboratorio"><span class="header-section-number">4.20</span> Aplicacion - Laboratorio</h2>
<div class="aplicacion-box" title="Aplicacion - Laboratorio">
<p><strong>Objetivo:</strong> Determinar experimentalmente el reactivo límite en la reacción entre bicarbonato de sodio y vinagre.</p>
<p><strong>Materiales:</strong> - Bicarbonato de sodio (<span class="math inline">\(NaHCO_3\)</span>) - Vinagre blanco (solución de ácido acético <span class="math inline">\(CH_3COOH\)</span> al 5%) - Balanza digital - 2 vasos desechables pequeños - Cuchara plástica</p>
<p><strong>Procedimiento:</strong> 1. Mide 5.0 g de bicarbonato de sodio y colócalos en un vaso. 2. Mide 30 mL de vinagre en el segundo vaso. 3. Agrega el vinagre al bicarbonato y observa la efervescencia. 4. Una vez que la reacción se detenga, verifica si quedó bicarbonato sin reaccionar en el fondo (toca con la cuchara). 5. Repite el experimento invirtiendo las cantidades: 30 g de bicarbonato y 5 mL de vinagre.</p>
<p><strong>Resultados:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Ensayo</th>
<th><span class="math inline">\(NaHCO_3\)</span> (g)</th>
<th>Vinagre (mL)</th>
<th>¿Sobró bicarbonato?</th>
<th>Reactivo límite</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>5.0</td>
<td>30</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>30</td>
<td>5</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Conclusion:</strong> Basado en tus observaciones, ¿qué ensayo tuvo el vinagre como reactivo límite? ¿Cómo lo sabes?</p>
<p></p>
<p></p>
<p></p>
</div>
</section>
<section id="evaluacion-tipo-icfes" class="level2 evaluacion-box-heading" data-number="4.21">
<h2 class="evaluacion-box-heading anchored" data-number="4.21" data-anchor-id="evaluacion-tipo-icfes"><span class="header-section-number">4.21</span> Evaluacion - tipo ICFES</h2>
<div class="evaluacion-box" title="Evaluacion - tipo ICFES">
<p><strong>Pregunta 1</strong> — Nivel Bajo</p>
<p><em>Contexto:</em> En la reacción <span class="math inline">\(N_2 + 3H_2 \rightarrow 2NH_3\)</span>, un estudiante dispone de 2 moles de <span class="math inline">\(N_2\)</span> y 4 moles de <span class="math inline">\(H_2\)</span>.</p>
<p><em>Enunciado:</em> De acuerdo con la información anterior, ¿cuál de las siguientes afirmaciones es correcta?</p>
<p>A. El <span class="math inline">\(N_2\)</span> es el reactivo límite porque su coeficiente estequiométrico es 1. B. El <span class="math inline">\(H_2\)</span> es el reactivo límite porque 4 ÷ 3 &lt; 2 ÷ 1. C. El <span class="math inline">\(N_2\)</span> y el <span class="math inline">\(H_2\)</span> están en proporción estequiométrica exacta. D. El <span class="math inline">\(H_2\)</span> es el reactivo límite porque hay menos moles de <span class="math inline">\(H_2\)</span> que de <span class="math inline">\(N_2\)</span>.</p>
<p><strong>Pregunta 2</strong> — Nivel Bajo</p>
<p><em>Contexto:</em> La ecuación <span class="math inline">\(2H_2 + O_2 \rightarrow 2H_2O\)</span> representa la formación de agua.</p>
<p><em>Enunciado:</em> Si se tienen 4 g de <span class="math inline">\(H_2\)</span> y 32 g de <span class="math inline">\(O_2\)</span>, ¿cuál de las siguientes opciones describe correctamente la situación? (Masas molares: <span class="math inline">\(H_2\)</span> = 2 g/mol, <span class="math inline">\(O_2\)</span> = 32 g/mol)</p>
<p>A. El oxígeno es el reactivo límite porque 32 g &gt; 4 g. B. El hidrógeno es el reactivo límite porque 2 ÷ 2 = 1 y 1 ÷ 1 = 1, están en proporción exacta. C. El oxígeno es el reactivo límite porque 1 ÷ 1 = 1 y 2 ÷ 2 = 1, ambos están igual. D. No hay reactivo límite porque ambos están en la proporción estequiométrica correcta.</p>
<p><strong>Pregunta 3</strong> — Nivel Medio</p>
<p><em>Contexto:</em> En un laboratorio se hacen reaccionar 10.0 g de calcio (Ca) con 10.0 g de oxígeno (<span class="math inline">\(O_2\)</span>) según la ecuación <span class="math inline">\(2Ca + O_2 \rightarrow 2CaO\)</span> (masas molares: Ca = 40.08 g/mol, <span class="math inline">\(O_2\)</span> = 32.00 g/mol, CaO = 56.08 g/mol).</p>
<p><em>Enunciado:</em> ¿Cuál es la masa máxima de CaO que se puede obtener?</p>
<p>A. 7.0 g B. 14.0 g C. 20.0 g D. 28.0 g</p>
<p><strong>Pregunta 4</strong> — Nivel Medio</p>
<p><em>Contexto:</em> La fermentación de la glucosa produce etanol y dióxido de carbono: <span class="math inline">\(C_6H_{12}O_6 \rightarrow 2C_2H_5OH + 2CO_2\)</span>. Un ingeniero dispone de 500 g de glucosa y obtiene 200 g de etanol (masas molares: glucosa = 180.16 g/mol, etanol = 46.07 g/mol).</p>
<p><em>Enunciado:</em> ¿Cuál es el rendimiento porcentual de la reacción?</p>
<p>A. 39.1% B. 68.5% C. 78.3% D. 100%</p>
<p><strong>Pregunta 5</strong> — Nivel Alto</p>
<p><em>Contexto:</em> En la tostación de la pirita (<span class="math inline">\(FeS_2\)</span>) para producir <span class="math inline">\(SO_2\)</span>, la ecuación es <span class="math inline">\(4FeS_2 + 11O_2 \rightarrow 2Fe_2O_3 + 8SO_2\)</span>. Un mineral contiene 240 g de <span class="math inline">\(FeS_2\)</span> con impurezas inertes y se usa oxígeno en exceso, obteniéndose 192 g de <span class="math inline">\(SO_2\)</span> (masas molares: <span class="math inline">\(FeS_2\)</span> = 119.98 g/mol, <span class="math inline">\(SO_2\)</span> = 64.06 g/mol).</p>
<p><em>Enunciado:</em> ¿Cuál es el porcentaje de pureza del mineral?</p>
<p>A. 50.0% B. 62.5% C. 75.0% D. 87.5%</p>
</div>
</section>
<section id="socializacion" class="level2 evaluacion-box-heading" data-number="4.22">
<h2 class="evaluacion-box-heading anchored" data-number="4.22" data-anchor-id="socializacion"><span class="header-section-number">4.22</span> Socializacion</h2>
<div class="evaluacion-box" title="Socializacion">
<p><strong>Pregunta 1</strong> — Nivel Bajo <em>Competencia:</em> Interpretación <em>Afirmacion:</em> Comprende las relaciones estequiométricas en una ecuación química balanceada. <em>Evidencia:</em> Identifica correctamente el reactivo límite dividiendo los moles disponibles entre los coeficientes estequiométricos. <em>Respuesta correcta:</em> B <em>Explicacion:</em> El cociente para <span class="math inline">\(N_2\)</span> es 2 ÷ 1 = 2, y para <span class="math inline">\(H_2\)</span> es 4 ÷ 3 ≈ 1.33. Como 1.33 &lt; 2, el <span class="math inline">\(H_2\)</span> es el reactivo límite.</p>
<p><strong>Pregunta 2</strong> — Nivel Bajo <em>Competencia:</em> Argumentación <em>Afirmacion:</em> Justifica la identificación del reactivo límite basándose en cálculos estequiométricos. <em>Evidencia:</em> Reconoce que cuando los cocientes moles ÷ coeficiente son iguales, los reactivos están en proporción estequiométrica exacta y no hay reactivo límite. <em>Respuesta correcta:</em> D <em>Explicacion:</em> <span class="math inline">\(H_2\)</span>: 2 mol ÷ 2 = 1; <span class="math inline">\(O_2\)</span>: 1 mol ÷ 1 = 1. Al ser iguales, ambos reactivos se consumen completamente y no hay reactivo límite.</p>
<p><strong>Pregunta 3</strong> — Nivel Medio <em>Competencia:</em> Interpretación <em>Afirmacion:</em> Determina la cantidad de producto a partir del reactivo límite. <em>Evidencia:</em> Calcula los moles de cada reactivo y del producto usando relaciones estequiométricas. <em>Respuesta correcta:</em> B <em>Explicacion:</em> Ca: 10.0 ÷ 40.08 = 0.249 mol, cociente = 0.249 ÷ 2 = 0.1245. <span class="math inline">\(O_2\)</span>: 10.0 ÷ 32.00 = 0.3125 mol, cociente = 0.3125 ÷ 1 = 0.3125. El Ca es el reactivo límite. Masa de CaO = 0.249 mol × (2 ÷ 2) × 56.08 g/mol = 14.0 g.</p>
<p><strong>Pregunta 4</strong> — Nivel Medio <em>Competencia:</em> Argumentación <em>Afirmacion:</em> Calcula el rendimiento porcentual de una reacción. <em>Evidencia:</em> Relaciona el rendimiento real con el rendimiento teórico usando la fórmula del porcentaje de rendimiento. <em>Respuesta correcta:</em> C <em>Explicacion:</em> Moles de glucosa = 500 ÷ 180.16 = 2.775 mol. Rendimiento teórico de etanol = 2.775 × 2 × 46.07 = 255.6 g. % rendimiento = (200 ÷ 255.6) × 100 = 78.3%.</p>
<p><strong>Pregunta 5</strong> — Nivel Alto <em>Competencia:</em> Proposición <em>Afirmacion:</em> Propone estrategias para determinar la pureza de un mineral a partir de datos experimentales. <em>Evidencia:</em> Relaciona la masa de producto obtenida con la masa del reactivo puro necesaria, usando la estequiometría de la reacción. <em>Respuesta correcta:</em> C <em>Explicacion:</em> Moles de <span class="math inline">\(SO_2\)</span> = 192 ÷ 64.06 = 3.0 mol. Moles de <span class="math inline">\(FeS_2\)</span> puro = 3.0 × (4 ÷ 8) = 1.5 mol. Masa de <span class="math inline">\(FeS_2\)</span> puro = 1.5 × 119.98 = 180 g. Pureza = (180 ÷ 240) × 100 = 75%.</p>
</div>
</section>
<section id="socioemocional" class="level2 socioemocional-box-heading" data-number="4.23">
<h2 class="socioemocional-box-heading anchored" data-number="4.23" data-anchor-id="socioemocional"><span class="header-section-number">4.23</span> Socioemocional</h2>
<div class="socioemocional-box" title="Socioemocional">
<p>Al aprender sobre el reactivo límite, es normal sentir que hay muchos pasos y cálculos que recordar. La clave está en la <strong>regulación emocional</strong>: reconocer que la frustración inicial es parte del proceso de aprendizaje y que cada paso resuelto es un logro. Identificar el reactivo límite en química es como identificar aquello que nos limita en la vida: cuando sabemos qué nos está frenando, podemos concentrar nuestros esfuerzos en eso y avanzar. Tú ya has superado conceptos difíciles antes; este es solo un escalón más. Respira, organiza tus pasos como organizas los cálculos, y verás que el resultado llega.</p>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-brown2022chemistry" class="csl-entry" role="listitem">
Brown, Theodore L., H. Eugene LeMay, Bruce E. Bursten, Catherine J. Murphy, Patrick M. Woodward, and Matthew W. Stoltzfus. 2022. <em>Chemistry: The Central Science</em>. 15th ed. Pearson.
</div>
<div id="ref-chang2017quimica" class="csl-entry" role="listitem">
Chang, Raymond, and Kenneth A. Goldsby. 2017. <em>Química</em>. 12th ed. McGraw-Hill Interamericana.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/camilotayac\.github\.io\/docere\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../01_Generalidades/02_PlanDeArea.html" class="pagination-link" aria-label="Plan de Área de Ciencias Naturales">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Plan de Área de Ciencias Naturales</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../bibliografia.html" class="pagination-link" aria-label="Referencias">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Referencias</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2025, Camilo Tayac</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/camilotayac/docere/edit/main/06_Decimo/reactivo_limite.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>