<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Teorema del seno – Natura Docens</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../bibliografia.html" rel="next">
<link href="../06_Decimo/escritura_quimica.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b9eaee60a963b5d74e9d33cc267de6a6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../_styles/headings.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Teorema del seno</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Natura Docens</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/camilotayac/docere/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Descargar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Descargar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../natura-docens.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Descargar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../natura-docens.epub">
              <i class="bi bi-journal pe-1"></i>
            Descargar ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Compartir" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Compartir"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Generalidades</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Estructura del libro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_Generalidades/01_Introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Generalidades</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_Generalidades/02_PlanDeArea.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Plan de Área de Ciencias Naturales</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Décimo - Química</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06_Decimo/reactivo_limite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reactivo límite</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06_Decimo/escritura_quimica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Escritura de ecuaciones químicas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Décimo - Matemáticas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06_Decimo/teorema_del_seno.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Teorema del seno</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../bibliografia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Referencias</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#teoría" id="toc-teoría" class="nav-link active" data-scroll-target="#teoría"><span class="header-section-number">6.1</span> Teoría</a></li>
  <li><a href="#ideas-previas" id="toc-ideas-previas" class="nav-link" data-scroll-target="#ideas-previas"><span class="header-section-number">6.2</span> Ideas Previas</a></li>
  <li><a href="#contextualización-método-feynman" id="toc-contextualización-método-feynman" class="nav-link" data-scroll-target="#contextualización-método-feynman"><span class="header-section-number">6.3</span> Contextualización — Método Feynman</a></li>
  <li><a href="#caracterizados-tdah" id="toc-caracterizados-tdah" class="nav-link" data-scroll-target="#caracterizados-tdah"><span class="header-section-number">6.4</span> Caracterizados — TDAH</a></li>
  <li><a href="#caracterizados-visual" id="toc-caracterizados-visual" class="nav-link" data-scroll-target="#caracterizados-visual"><span class="header-section-number">6.5</span> Caracterizados — Visual</a></li>
  <li><a href="#caracterizados-dislexia" id="toc-caracterizados-dislexia" class="nav-link" data-scroll-target="#caracterizados-dislexia"><span class="header-section-number">6.6</span> Caracterizados — Dislexia</a></li>
  <li><a href="#caracterizados-autismo" id="toc-caracterizados-autismo" class="nav-link" data-scroll-target="#caracterizados-autismo"><span class="header-section-number">6.7</span> Caracterizados — Autismo</a></li>
  <li><a href="#caracterizados-accesibilidad-sensorial" id="toc-caracterizados-accesibilidad-sensorial" class="nav-link" data-scroll-target="#caracterizados-accesibilidad-sensorial"><span class="header-section-number">6.8</span> Caracterizados — Accesibilidad Sensorial</a></li>
  <li><a href="#caracterizados-socioemocional" id="toc-caracterizados-socioemocional" class="nav-link" data-scroll-target="#caracterizados-socioemocional"><span class="header-section-number">6.9</span> Caracterizados — Socioemocional</a></li>
  <li><a href="#ejemplo-nivel-bajo" id="toc-ejemplo-nivel-bajo" class="nav-link" data-scroll-target="#ejemplo-nivel-bajo"><span class="header-section-number">6.10</span> Ejemplo — Nivel Bajo</a></li>
  <li><a href="#ejemplo-nivel-medio" id="toc-ejemplo-nivel-medio" class="nav-link" data-scroll-target="#ejemplo-nivel-medio"><span class="header-section-number">6.11</span> Ejemplo — Nivel Medio</a></li>
  <li><a href="#ejemplo-nivel-alto" id="toc-ejemplo-nivel-alto" class="nav-link" data-scroll-target="#ejemplo-nivel-alto"><span class="header-section-number">6.12</span> Ejemplo — Nivel Alto</a></li>
  <li><a href="#ejercicios-nivel-bajo" id="toc-ejercicios-nivel-bajo" class="nav-link" data-scroll-target="#ejercicios-nivel-bajo"><span class="header-section-number">6.13</span> Ejercicios — Nivel Bajo</a></li>
  <li><a href="#ejercicios-nivel-medio" id="toc-ejercicios-nivel-medio" class="nav-link" data-scroll-target="#ejercicios-nivel-medio"><span class="header-section-number">6.14</span> Ejercicios — Nivel Medio</a></li>
  <li><a href="#ejercicios-nivel-alto" id="toc-ejercicios-nivel-alto" class="nav-link" data-scroll-target="#ejercicios-nivel-alto"><span class="header-section-number">6.15</span> Ejercicios — Nivel Alto</a></li>
  <li><a href="#retos" id="toc-retos" class="nav-link" data-scroll-target="#retos"><span class="header-section-number">6.16</span> Retos</a></li>
  <li><a href="#aplicación-vida-real" id="toc-aplicación-vida-real" class="nav-link" data-scroll-target="#aplicación-vida-real"><span class="header-section-number">6.17</span> Aplicación — Vida real</a></li>
  <li><a href="#aplicación-laboratorio" id="toc-aplicación-laboratorio" class="nav-link" data-scroll-target="#aplicación-laboratorio"><span class="header-section-number">6.18</span> Aplicación — Laboratorio</a></li>
  <li><a href="#evaluación-tipo-icfes" id="toc-evaluación-tipo-icfes" class="nav-link" data-scroll-target="#evaluación-tipo-icfes"><span class="header-section-number">6.19</span> Evaluación — Tipo ICFES</a></li>
  <li><a href="#socialización" id="toc-socialización" class="nav-link" data-scroll-target="#socialización"><span class="header-section-number">6.20</span> Socialización</a></li>
  <li><a href="#socioemocional" id="toc-socioemocional" class="nav-link" data-scroll-target="#socioemocional"><span class="header-section-number">6.21</span> Socioemocional</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/camilotayac/docere/edit/main/06_Decimo/teorema_del_seno.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Teorema del seno</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="teoría" class="level2 teoria" data-number="6.1">
<h2 class="teoria anchored" data-number="6.1" data-anchor-id="teoría"><span class="header-section-number">6.1</span> Teoría</h2>
<p>La <strong>trigonometría</strong> es la rama de las matemáticas que estudia las relaciones entre los lados y los ángulos de los triángulos. El <strong>teorema del seno</strong> (o ley de senos) establece una proporción constante entre la longitud de cada lado de un triángulo y el seno del ángulo opuesto a dicho lado. Para cualquier triángulo <span class="math inline">\(ABC\)</span> con lados <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span> opuestos a los vértices <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span> y <span class="math inline">\(C\)</span> respectivamente, se cumple:</p>
<p><span class="math display">\[ \frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C} = 2R \tag{1} \]</span></p>
<p>Donde <span class="math inline">\(R\)</span> es el radio de la <strong>circunferencia circunscrita</strong> (círculo que pasa por los tres vértices del triángulo) <span class="citation" data-cites="stewart2015precalculo">(<a href="../bibliografia.html#ref-stewart2015precalculo" role="doc-biblioref">Stewart et&nbsp;al. 2015</a>)</span>.</p>
<p>El teorema del seno es particularmente útil para resolver triángulos oblicuángulos (triángulos que no tienen un ángulo recto) cuando se conocen:</p>
<ul>
<li><strong>Dos ángulos y un lado (AAL o ALA):</strong> se encuentra el tercer ángulo usando la suma <span class="math inline">\(A + B + C = 180^\circ\)</span> y luego se aplica la ley de senos para hallar los lados restantes.</li>
<li><strong>Dos lados y un ángulo no comprendido (LLA):</strong> conocido como el <strong>caso ambiguo</strong>, puede producir cero, una o dos soluciones posibles dependiendo de las longitudes relativas.</li>
</ul>
<p><strong>Caso ambiguo (LLA):</strong> Dados dos lados <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span> y el ángulo <span class="math inline">\(A\)</span> opuesto al lado <span class="math inline">\(a\)</span>:</p>
<ul>
<li>Si <span class="math inline">\(a &lt; b\sin A\)</span>: no hay solución.</li>
<li>Si <span class="math inline">\(a = b\sin A\)</span>: una solución (triángulo rectángulo).</li>
<li>Si <span class="math inline">\(b\sin A &lt; a &lt; b\)</span>: dos soluciones (dos triángulos posibles).</li>
<li>Si <span class="math inline">\(a \geq b\)</span>: una solución.</li>
</ul>
<p>La constante <span class="math inline">\(2R\)</span> también permite calcular el área del triángulo mediante:</p>
<p><span class="math display">\[ \text{Área} = \frac{abc}{4R} \tag{2} \]</span></p>
<style>
.sim-seno {
  font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
  max-width: 100%;
  margin: 1.5em 0;
  padding: 1.8em;
  border-radius: 12px;
  background: linear-gradient(145deg, #ffffff, #f5f7fa);
  box-shadow: 0 4px 20px rgba(0,0,0,0.08);
  border: 1px solid #e0e4e8;
}
.sim-seno h3 {
  margin: 0 0 0.4em 0;
  font-size: 1.25em;
  color: #2c3e50;
  border-bottom: 2px solid #3498db;
  padding-bottom: 0.5em;
  display: inline-block;
}
.sim-seno .sim-row {
  display: flex;
  flex-wrap: wrap;
  gap: 1em;
  margin-bottom: 1em;
  align-items: end;
}
.sim-seno .sim-field {
  display: flex;
  flex-direction: column;
  gap: 0.25em;
}
.sim-seno .sim-field label {
  font-size: 0.8em;
  font-weight: 700;
  color: #555;
  text-transform: uppercase;
  letter-spacing: 0.03em;
}
.sim-seno .sim-field input,
.sim-seno .sim-field select {
  padding: 0.5em 0.7em;
  font-size: 1em;
  border: 2px solid #dce1e8;
  border-radius: 8px;
  width: 110px;
  font-family: inherit;
  transition: border-color 0.2s;
  background: #fff;
}
.sim-seno .sim-field input:focus,
.sim-seno .sim-field select:focus {
  border-color: #3498db;
  outline: none;
  box-shadow: 0 0 0 3px rgba(52,152,219,0.15);
}
.sim-seno .sim-btn {
  padding: 0.55em 1.4em;
  font-size: 0.95em;
  font-weight: 600;
  border: none;
  border-radius: 8px;
  background: #3498db;
  color: #fff;
  cursor: pointer;
  font-family: inherit;
  transition: background 0.2s, transform 0.1s;
}
.sim-seno .sim-btn:hover { background: #2980b9; }
.sim-seno .sim-btn:active { transform: scale(0.97); }
.sim-seno .sim-btn.sec {
  background: #95a5a6;
}
.sim-seno .sim-btn.sec:hover { background: #7f8c8d; }
.sim-seno .sim-result {
  margin-top: 1.2em;
  padding: 1.2em;
  border-radius: 10px;
  background: #fff;
  border: 1px solid #e8ecf0;
  white-space: pre-wrap;
  font-size: 0.95em;
  line-height: 1.7;
  min-height: 2em;
}
.sim-seno .sim-result .ok {
  display: inline-block;
  background: #e8f8f0;
  color: #1a7a3a;
  font-weight: 700;
  padding: 0.2em 0.8em;
  border-radius: 4px;
}
.sim-seno .sim-result .err {
  display: inline-block;
  background: #fde8e8;
  color: #c0392b;
  font-weight: 700;
  padding: 0.2em 0.8em;
  border-radius: 4px;
}
.sim-seno .sim-result .hl  { color: #2c3e50; font-weight: 700; }
.sim-seno .sim-info {
  font-size: 0.88em;
  color: #666;
  margin-bottom: 1.2em;
  padding: 0.6em 0.8em;
  background: #f0f4f9;
  border-radius: 6px;
}
.sim-seno .sim-tabla {
  margin-top: 0.6em;
  border-collapse: collapse;
  font-size: 0.9em;
}
.sim-seno .sim-tabla td {
  padding: 0.25em 1em 0.25em 0;
  border: none;
}
.sim-seno .sim-tabla .label { color: #888; font-weight: 600; }
.sim-seno .sim-tabla .val { font-weight: 600; color: #2c3e50; }
.sim-seno .sim-k {
  display: inline-block;
  margin-top: 0.6em;
  padding: 0.5em 1em;
  background: #eef4fb;
  border-radius: 6px;
  font-weight: 700;
  color: #2980b9;
  border-left: 4px solid #3498db;
}
.sol-box {
  margin: 0.5em 0;
  padding: 0.6em 1em;
  background: #f8fafc;
  border-radius: 6px;
  border-left: 3px solid #3498db;
}
.sol-box .sol-title {
  font-weight: 700;
  color: #2c3e50;
  margin-bottom: 0.3em;
}
</style>
<div class="sim-seno" id="sim-seno-app">
  <h3 class="anchored">Calculadora - Teorema del seno</h3>
  <div class="sim-info">Ingresa los datos del triángulo. El simulador calculará los lados y ángulos faltantes usando <i>a</i>/sen <i>A</i> = <i>b</i>/sen <i>B</i> = <i>c</i>/sen <i>C</i>.</div>
  <div class="sim-row">
    <div class="sim-field">
      <label for="sim-modo">Modo</label>
      <select id="sim-modo">
        <option value="AAL">Dos ángulos + un lado (AAL)</option>
        <option value="LLA">Dos lados + ángulo no comprendido (LLA)</option>
      </select>
    </div>
  </div>
  <div class="sim-row" id="sim-inputs-AAL">
    <div class="sim-field"><label>A (°)</label><input type="number" id="sim-aal-A" value="40" step="any"></div>
    <div class="sim-field"><label>B (°)</label><input type="number" id="sim-aal-B" value="60" step="any"></div>
    <div class="sim-field"><label>a</label><input type="number" id="sim-aal-a" value="10" step="any"></div>
  </div>
  <div class="sim-row" id="sim-inputs-LLA" style="display:none">
    <div class="sim-field"><label>a</label><input type="number" id="sim-lla-a" value="12" step="any"></div>
    <div class="sim-field"><label>b</label><input type="number" id="sim-lla-b" value="8" step="any"></div>
    <div class="sim-field"><label>A (°)</label><input type="number" id="sim-lla-A" value="35" step="any"></div>
  </div>
  <div class="sim-row">
    <button class="sim-btn" id="sim-calcular">Calcular</button>
    <button class="sim-btn sec" id="sim-limpiar">Limpiar</button>
  </div>
  <div class="sim-result" id="sim-resultado">Presiona <b>Calcular</b> para resolver el triángulo.</div>
</div>
<script>
(function() {
  var app = document.getElementById('sim-seno-app');
  if (!app) return;
  var modo = document.getElementById('sim-modo');
  var aal = document.getElementById('sim-inputs-AAL');
  var lla = document.getElementById('sim-inputs-LLA');
  var resultado = document.getElementById('sim-resultado');
  var btnCalc = document.getElementById('sim-calcular');
  var btnLimpiar = document.getElementById('sim-limpiar');
  function mostrarInputs() {
    var m = modo.value;
    aal.style.display = m === 'AAL' ? '' : 'none';
    lla.style.display = m === 'LLA' ? '' : 'none';
  }
  modo.addEventListener('change', mostrarInputs);
  mostrarInputs();
  function g(id) { return parseFloat(document.getElementById(id).value); }
  function fmt(v) {
    if (isNaN(v)) return '&mdash;';
    var s = v.toFixed(3);
    if (s.indexOf('.') > -1) s = s.replace(/\.?0+$/, '');
    return s;
  }
  function resolverAAL() {
    var A = g('sim-aal-A'), B = g('sim-aal-B'), a = g('sim-aal-a');
    if (isNaN(A) || isNaN(B) || isNaN(a)) return { error: 'Ingresa valores num&eacute;ricos v&aacute;lidos.' };
    if (A <= 0 || B <= 0) return { error: 'Los &aacute;ngulos deben ser positivos.' };
    if (A + B >= 180) return { error: 'La suma A + B debe ser menor a 180&deg;.' };
    var C = 180 - A - B;
    if (C <= 0) return { error: 'El &aacute;ngulo C debe ser positivo. Revisa A y B.' };
    var rad = Math.PI / 180;
    var senA = Math.sin(A * rad), senB = Math.sin(B * rad), senC = Math.sin(C * rad);
    var k = a / senA;
    var b = k * senB, c = k * senC;
    var R = k / 2;
    return { A: A, B: B, C: C, a: a, b: b, c: c, k: k, R: R, senA: senA, senB: senB, senC: senC };
  }
  function resolverLLA() {
    var a = g('sim-lla-a'), b = g('sim-lla-b'), A = g('sim-lla-A');
    if (isNaN(a) || isNaN(b) || isNaN(A)) return { error: 'Ingresa valores num&eacute;ricos v&aacute;lidos.' };
    if (a <= 0 || b <= 0) return { error: 'Los lados deben ser positivos.' };
    if (A <= 0 || A >= 180) return { error: 'El &aacute;ngulo A debe estar entre 0&deg; y 180&deg;.' };
    var rad = Math.PI / 180;
    var senA = Math.sin(A * rad);
    var k = a / senA;
    var senB = (b * senA) / a;
    if (senB > 1.0001) return { error: 'No hay soluci&oacute;n: sen B &gt; 1. Intenta con otros valores.' };
    if (senB > 1) senB = 1;
    var B1 = Math.asin(senB) / rad;
    var B2 = 180 - B1;
    var sols = [];
    var casos = [];
    if (a < b * senA - 1e-9) {
      return { error: 'No hay soluci&oacute;n: a &lt; b &middot; sen A.' };
    } else if (Math.abs(a - b * senA) < 1e-9) {
      casos = [B1];
    } else if (a < b - 1e-9) {
      casos = [B1, B2];
    } else {
      casos = [B1];
    }
    for (var i = 0; i < casos.length; i++) {
      var B = casos[i];
      if (B <= 0 || B >= 180) continue;
      var C = 180 - A - B;
      if (C <= 0 || C >= 180) continue;
      var senC = Math.sin(C * rad);
      var c = k * senC;
      sols.push({ A: A, B: B, C: C, a: a, b: b, c: c, k: k, R: k/2, senA: senA, senB: Math.sin(B * rad), senC: senC });
    }
    return { sols: sols };
  }
  function mostrar(res) {
    var h = '';
    if (res.error) {
      h = '<span class="err">' + res.error + '</span>';
    } else if (res.sols !== undefined) {
      if (res.sols.length === 0) {
        h = '<span class="err">No hay soluci&oacute;n v&aacute;lida para los datos dados.</span>';
      } else {
        h += '<span class="hl" style="font-size:1.05em">' + res.sols.length + ' soluci&oacute;n(es) posible(s)</span>';
        for (var i = 0; i < res.sols.length; i++) {
          var s = res.sols[i];
          h += '<div class="sol-box"><div class="sol-title">Soluci&oacute;n ' + (i+1) + '</div>';
          h += '<table class="sim-tabla"><tr><td class="label">Angulos:</td><td class="val">A = ' + fmt(s.A) + '&deg;</td><td class="val">B = ' + fmt(s.B) + '&deg;</td><td class="val">C = ' + fmt(s.C) + '&deg;</td></tr>';
          h += '<tr><td class="label">Lados:</td><td class="val">a = ' + fmt(s.a) + '</td><td class="val">b = ' + fmt(s.b) + '</td><td class="val">c = ' + fmt(s.c) + '</td></tr>';
          h += '</table><div class="sim-k">\\( \\displaystyle \\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = ' + fmt(s.k) + ' \\) &nbsp;|&nbsp; \\( 2R = ' + fmt(s.k) + ' \\) &nbsp;|&nbsp; \\( R = ' + fmt(s.R) + ' \\)</div></div>';
        }
      }
    } else {
      h = '<span class="ok">Tri&aacute;ngulo resuelto</span>';
      h += '<table class="sim-tabla"><tr><td class="label">Angulos:</td><td class="val">A = ' + fmt(res.A) + '&deg;</td><td class="val">B = ' + fmt(res.B) + '&deg;</td><td class="val">C = ' + fmt(res.C) + '&deg;</td></tr>';
      h += '<tr><td class="label">Lados:</td><td class="val">a = ' + fmt(res.a) + '</td><td class="val">b = ' + fmt(res.b) + '</td><td class="val">c = ' + fmt(res.c) + '</td></tr>';
      h += '</table>';
      h += '<div class="sim-k">\\( \\displaystyle \\frac{a}{\\sin A} = \\frac{' + fmt(res.a) + '}{' + fmt(res.senA) + '} = ' + fmt(res.k) + ' \\)<br>';
      h += '\\( \\displaystyle \\frac{b}{\\sin B} = \\frac{' + fmt(res.b) + '}{' + fmt(res.senB) + '} = ' + fmt(res.k) + ' \\)<br>';
      h += '\\( \\displaystyle \\frac{c}{\\sin C} = \\frac{' + fmt(res.c) + '}{' + fmt(res.senC) + '} = ' + fmt(res.k) + ' \\)<br>';
      h += '\\( \\displaystyle 2R = ' + fmt(res.k) + ' \\Rightarrow R = ' + fmt(res.R) + ' \\)</div>';
    }
    resultado.innerHTML = h;
    try { if (window.MathJax && MathJax.typesetPromise) MathJax.typesetPromise([resultado]); } catch(e) {}
  }
  btnCalc.addEventListener('click', function() {
    var m = modo.value;
    var r = m === 'AAL' ? resolverAAL() : resolverLLA();
    mostrar(r);
  });
  btnLimpiar.addEventListener('click', function() {
    if (modo.value === 'AAL') {
      document.getElementById('sim-aal-A').value = '';
      document.getElementById('sim-aal-B').value = '';
      document.getElementById('sim-aal-a').value = '';
    } else {
      document.getElementById('sim-lla-a').value = '';
      document.getElementById('sim-lla-b').value = '';
      document.getElementById('sim-lla-A').value = '';
    }
    resultado.innerHTML = 'Valores limpiados. Ingresa nuevos datos y presiona <b>Calcular</b>.';
  });
  app.addEventListener('keydown', function(e) {
    if (e.key === 'Enter') btnCalc.click();
  });
})();
</script>
</section>
<section id="ideas-previas" class="level2 ideas-previas" data-number="6.2">
<h2 class="ideas-previas anchored" data-number="6.2" data-anchor-id="ideas-previas"><span class="header-section-number">6.2</span> Ideas Previas</h2>
<p>Imagina que estás en el Parque Arqueológico de San Agustín (Huila) y encuentras dos estatuas precolombinas separadas por una quebrada. No puedes cruzar directamente, pero puedes medir la distancia desde donde estás hasta cada estatua y el ángulo entre esas dos líneas de visión. Con esa información, un arqueólogo podría determinar la distancia exacta entre las dos estatuas.</p>
<ul>
<li><p><strong>¿Qué crees que necesitas saber para calcular la distancia entre dos puntos que no puedes medir directamente?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p><strong>¿Recuerdas qué es el seno de un ángulo en un triángulo rectángulo? ¿Cómo se define?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p><strong>Si conoces dos ángulos de un triángulo, ¿puedes determinar el tercero? ¿Cómo?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p><strong>¿En qué situaciones de la vida cotidiana crees que es necesario medir distancias sin poder usar una cinta métrica directamente?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p><strong>¿Qué relación crees que existe entre el tamaño de un lado de un triángulo y el ángulo que está frente a ese lado?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p><strong>¿Has visto algún instrumento que usen los topógrafos o constructores para medir ángulos en el terreno?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p><strong>Si tuvieras que encontrar la altura de un cerro sin escalarlo, ¿qué datos necesitarías?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p><strong>¿Por qué piensas que es importante para un ingeniero conocer la distancia exacta entre dos puntos separados por un obstáculo?</strong></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
</ul>
<p>En el municipio de Monguí (Boyacá), los topógrafos del Instituto Geográfico Agustín Codazzi (IGAC) miden regularmente las montañas usando triangulación. Se colocan en dos puntos conocidos y miden ángulos hacia un tercer punto inaccesible (como la cima de una montaña). Con esos datos y el teorema del seno, calculan distancias y alturas sin necesidad de escalar el terreno. Este mismo principio se usó en el siglo XVIII para medir el meridiano terrestre en la Misión Geodésica Francesa que pasó por territorio colombiano.</p>
</section>
<section id="contextualización-método-feynman" class="level2 contexto" data-number="6.3">
<h2 class="contexto anchored" data-number="6.3" data-anchor-id="contextualización-método-feynman"><span class="header-section-number">6.3</span> Contextualización — Método Feynman</h2>
<p>Imagina que estás en la Plaza de Bolívar de Bogotá y quieres saber la distancia entre la estatua de Bolívar y la entrada de la Catedral Primada, pero hay una fuente de por medio que te impide medir directamente. Te colocas en un punto cualquiera, mides tu distancia a la estatua (digamos <span class="math inline">\(20\)</span> m), mides tu distancia a la catedral (<span class="math inline">\(25\)</span> m), y con un transportador mides el ángulo entre esas dos líneas (<span class="math inline">\(40^\circ\)</span>). Ahora tienes un triángulo donde conoces dos lados y el ángulo entre ellos. ¿Y si en lugar de eso conocieras un lado y dos ángulos? El teorema del seno te permite resolver cualquier triángulo oblicuángulo con esa información. La clave está en que la razón entre un lado y el seno de su ángulo opuesto es constante para los tres pares lado-ángulo. Es como si cada lado “gritara” su propia longitud dividida por el seno de su ángulo opuesto, y todos gritaran el mismo número. Cuidado: el teorema del seno no es directamente aplicable a triángulos rectángulos como una novedad — en esos casos se sigue usando el teorema de Pitágoras y las razones trigonométricas básicas, aunque el teorema del seno también funciona.</p>
</section>
<section id="caracterizados-tdah" class="level2 caracterizados" data-number="6.4">
<h2 class="caracterizados anchored" data-number="6.4" data-anchor-id="caracterizados-tdah"><span class="header-section-number">6.4</span> Caracterizados — TDAH</h2>
<p>Resolver un triángulo con el teorema del seno es un juego de <span class="math inline">\(3\)</span> movimientos. Antes de empezar, visualiza esto: tienes un triángulo con tres ángulos (<span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(C\)</span>) y tres lados (<span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span>). El teorema del seno dice que <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}\)</span>. Es como una balanza de tres platillos que siempre está equilibrada. <strong>Movimiento 1:</strong> identifica qué datos te dan y qué necesitas encontrar. <strong>Movimiento 2:</strong> elige la proporción que relaciona tus datos conocidos con la incógnita. <strong>Movimiento 3:</strong> despeja la incógnita y calcula. Si te dan dos ángulos, primero calcula el tercero restando de <span class="math inline">\(180^\circ\)</span> — ese es el <strong>Movimiento 0</strong>.</p>
<p><strong>Ejemplo:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 40^\circ\)</span>, <span class="math inline">\(B = 60^\circ\)</span>, <span class="math inline">\(a = 10\)</span> cm. Encuentra <span class="math inline">\(b\)</span>. Movimiento 0: <span class="math inline">\(C = 180^\circ - 40^\circ - 60^\circ = 80^\circ\)</span>. Movimiento 1: conozco <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(a\)</span>; quiero <span class="math inline">\(b\)</span>. Movimiento 2: uso <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B}\)</span>. Movimiento 3: <span class="math inline">\(b = \frac{a \cdot \sin B}{\sin A} = \frac{10 \cdot \sin 60^\circ}{\sin 40^\circ} = \frac{10 \cdot 0.8660}{0.6428} \approx 13.47\)</span> cm. <strong>Ahora tapa el cálculo y explica en voz alta por qué elegiste esa proporción y no otra.</strong></p>
<p><strong>Ejercicios:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 30^\circ\)</span>, <span class="math inline">\(C = 70^\circ\)</span>, <span class="math inline">\(b = 15\)</span> cm. Aplica los 3 movimientos para hallar <span class="math inline">\(a\)</span> y <span class="math inline">\(c\)</span>. <strong>[Opcional: explica en voz alta los pasos en vez de escribirlos.]</strong></p>
<p><strong>Metacognición:</strong> 1. Si conoces dos ángulos y un lado, ¿siempre puedes encontrar los otros dos lados? ¿Por qué? 2. ¿Qué movimiento se te hizo más fácil? ¿Cuál más difícil? 3. ¿Cómo sabes qué proporción usar si tienes <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span> y <span class="math inline">\(A\)</span> pero no <span class="math inline">\(B\)</span>?</p>
<p><strong>Opción de respuesta:</strong> Puedes responder escribiendo, dibujando o explicándoselo a un compañero.</p>
<p><strong>Glosario:</strong> - <strong>Seno:</strong> función trigonométrica que relaciona un ángulo con la razón entre el cateto opuesto y la hipotenusa en un triángulo rectángulo. - <strong>Triángulo oblicuángulo:</strong> triángulo que no tiene ningún ángulo recto. - <strong>Resolver un triángulo:</strong> encontrar todos los lados y ángulos desconocidos. - <strong>Circunferencia circunscrita:</strong> círculo que pasa por los tres vértices del triángulo.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
</section>
<section id="caracterizados-visual" class="level2 caracterizados" data-number="6.5">
<h2 class="caracterizados anchored" data-number="6.5" data-anchor-id="caracterizados-visual"><span class="header-section-number">6.5</span> Caracterizados — Visual</h2>
<p>Observa esta relación: en cualquier triángulo, la razón entre un lado y el seno del ángulo opuesto es constante. Esto significa que si dibujas un triángulo y prolongas sus lados hasta formar una circunferencia circunscrita, el diámetro de esa circunferencia es exactamente <span class="math inline">\(2R = \frac{a}{\sin A}\)</span>. Visualmente, lado más grande <span class="math inline">\(\rightarrow\)</span> seno de ángulo opuesto más grande <span class="math inline">\(\rightarrow\)</span> ángulo más grande. Ahora tradúcelo a números en esta tabla:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Relación</th>
<th style="text-align: center;">Lado</th>
<th style="text-align: center;">Ángulo opuesto</th>
<th style="text-align: center;">Seno del ángulo</th>
<th style="text-align: center;"><span class="math inline">\(\frac{\text{lado}}{\sin\text{ángulo}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(10\)</span></td>
<td style="text-align: center;"><span class="math inline">\(40^\circ\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sin 40^\circ \approx 0.6428\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{10}{0.6428} \approx 15.56\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(b\)</span></td>
<td style="text-align: center;"><span class="math inline">\(13.47\)</span></td>
<td style="text-align: center;"><span class="math inline">\(60^\circ\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sin 60^\circ \approx 0.8660\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{13.47}{0.8660} \approx 15.56\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(?\)</span></td>
<td style="text-align: center;"><span class="math inline">\(80^\circ\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sin 80^\circ \approx 0.9848\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{c}{0.9848} = 15.56\)</span></td>
</tr>
</tbody>
</table>
<p>La constante <span class="math inline">\(15.56\)</span> es el diámetro <span class="math inline">\(2R\)</span> de la circunferencia circunscrita. <strong>Ahora cubre los valores de la tabla y reconstruye el diagrama de flujo de memoria: identificar datos <span class="math inline">\(\rightarrow\)</span> elegir proporción <span class="math inline">\(\rightarrow\)</span> despejar <span class="math inline">\(\rightarrow\)</span> calcular.</strong></p>
<p><strong>Ejemplo:</strong> Para un triángulo con <span class="math inline">\(a = 7\)</span> cm, <span class="math inline">\(b = 9\)</span> cm, <span class="math inline">\(A = 35^\circ\)</span>, dibuja el triángulo a escala aproximada. El lado <span class="math inline">\(a\)</span> es más pequeño que <span class="math inline">\(b\)</span>, y el ángulo <span class="math inline">\(A\)</span> también debe ser menor que <span class="math inline">\(B\)</span>. Aplica <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B}\)</span> para hallar <span class="math inline">\(\sin B = \frac{b\sin A}{a}\)</span>.</p>
<p><strong>Ejercicios:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(a = 12\)</span> cm, <span class="math inline">\(b = 15\)</span> cm, <span class="math inline">\(\sin A = 0.4\)</span>. Completa una tabla como la de arriba para hallar <span class="math inline">\(\sin B\)</span>. <strong>[Opcional: dibuja el triángulo a escala en lugar de la tabla.]</strong></p>
<p><strong>Metacognición:</strong> 1. Dibuja un triángulo y la circunferencia que pasa por sus tres vértices. ¿Dónde está el diámetro <span class="math inline">\(2R\)</span>? 2. ¿Qué relación visual observas entre el lado más largo y el ángulo más grande? 3. Si el lado <span class="math inline">\(b\)</span> es el doble de <span class="math inline">\(a\)</span>, ¿el seno de <span class="math inline">\(B\)</span> será el doble del seno de <span class="math inline">\(A\)</span>?</p>
<p><strong>Opción de respuesta:</strong> Puedes responder escribiendo, dibujando o explicándoselo a un compañero.</p>
<p><strong>Glosario:</strong> - <strong>Circunferencia circunscrita:</strong> el círculo que rodea al triángulo pasando por sus tres vértices. - <strong>Diámetro:</strong> segmento que pasa por el centro de la circunferencia y la divide en dos partes iguales. - <strong>Razón constante:</strong> el valor que no cambia en las tres proporciones del teorema del seno.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
</section>
<section id="caracterizados-dislexia" class="level2 caracterizados" data-number="6.6">
<h2 class="caracterizados anchored" data-number="6.6" data-anchor-id="caracterizados-dislexia"><span class="header-section-number">6.6</span> Caracterizados — Dislexia</h2>
<p>El teorema del seno dice que en cualquier triangulo, el lado partido por el seno de su angulo opuesto da el mismo resultado para los tres lados. Es como una regla de tres: si sabes que <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B}\)</span>, entonces puedes despejar <span class="math inline">\(b = \frac{a \cdot \sin B}{\sin A}\)</span>. Solo tienes que asegurarte de que el lado y el angulo esten opuestos. <strong>Ahora tapa los pasos y dime en voz alta cual fue el primer paso: ¿que tenias que identificar primero?</strong></p>
<p><strong>Ejemplo:</strong> En un triangulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 50^\circ\)</span>, <span class="math inline">\(B = 70^\circ\)</span>, <span class="math inline">\(a = 8\)</span> cm. Primero calculas <span class="math inline">\(C = 180^\circ - 50^\circ - 70^\circ = 60^\circ\)</span>. Despues usas <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B}\)</span> para hallar <span class="math inline">\(b\)</span>: <span class="math inline">\(b = \frac{8 \cdot \sin 70^\circ}{\sin 50^\circ} = \frac{8 \cdot 0.9397}{0.7660} \approx 9.81\)</span> cm. Para hallar <span class="math inline">\(c\)</span> usas <span class="math inline">\(\frac{a}{\sin A} = \frac{c}{\sin C}\)</span>: <span class="math inline">\(c = \frac{8 \cdot \sin 60^\circ}{\sin 50^\circ} = \frac{8 \cdot 0.8660}{0.7660} \approx 9.05\)</span> cm. <strong>Sin mirar la solucion, explicale a un amigo de 10 años como resolviste esto.</strong></p>
<p><strong>Ejercicios:</strong> En un triangulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 45^\circ\)</span>, <span class="math inline">\(B = 65^\circ\)</span>, <span class="math inline">\(a = 10\)</span> cm. Halla <span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span>. <strong>[Opcional: graba un audio explicando el procedimiento en vez de escribirlo.]</strong></p>
<p><strong>Metacognición:</strong> 1. Sin leer la teoria otra vez, explica con tus palabras que dice el teorema del seno. 2. ¿Que pasa si no encuentras el angulo <span class="math inline">\(C\)</span> primero? ¿Puedes resolver el triangulo de todas formas? 3. ¿Hay algun paso donde te hayas trabado? ¿Que harías para que ese paso sea mas facil la proxima vez?</p>
<p><strong>Opción de respuesta:</strong> Puedes responder escribiendo, grabando un audio o explicándoselo a un compañero.</p>
<p><strong>Glosario:</strong> - <strong>Teorema del seno:</strong> regla que dice que el lado dividido por el seno del angulo opuesto da el mismo numero para los tres lados. - <strong>Angulo opuesto:</strong> el angulo que esta enfrente de un lado, sin tocarlo. - <strong>Seno:</strong> numero que resulta de dividir el cateto opuesto entre la hipotenusa en un triangulo rectangulo.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
</section>
<section id="caracterizados-autismo" class="level2 caracterizados" data-number="6.7">
<h2 class="caracterizados anchored" data-number="6.7" data-anchor-id="caracterizados-autismo"><span class="header-section-number">6.7</span> Caracterizados — Autismo</h2>
<p><strong>Regla fija:</strong> En cualquier triángulo <span class="math inline">\(ABC\)</span> se cumple que <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}\)</span>, donde <span class="math inline">\(a\)</span> es el lado opuesto al vértice <span class="math inline">\(A\)</span>, <span class="math inline">\(b\)</span> es el lado opuesto al vértice <span class="math inline">\(B\)</span>, y <span class="math inline">\(c\)</span> es el lado opuesto al vértice <span class="math inline">\(C\)</span>. Esta igualdad no es una aproximación ni depende del tipo de triángulo: es una propiedad exacta demostrada geométricamente. La constante <span class="math inline">\(2R\)</span> se obtiene al trazar la circunferencia circunscrita: el diámetro de esta circunferencia es exactamente igual a <span class="math inline">\(\frac{a}{\sin A}\)</span>.</p>
<p>ALGORITMO (caso AAL - dos ángulos y un lado): 1. Calcula el tercer ángulo: <span class="math inline">\(C = 180^\circ - A - B\)</span>. 2. Selecciona la proporción que relaciona el lado conocido con el lado buscado: <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B}\)</span>. 3. Despeja la incógnita: <span class="math inline">\(b = \frac{a \cdot \sin B}{\sin A}\)</span>. 4. Verifica que el resultado sea consistente: el lado más grande debe estar opuesto al ángulo más grande.</p>
<p>ALGORITMO (caso LLA - dos lados y ángulo no comprendido): 1. Calcula <span class="math inline">\(\sin B = \frac{b \cdot \sin A}{a}\)</span>. 2. Si <span class="math inline">\(\sin B &gt; 1\)</span>, no hay solución. 3. Si <span class="math inline">\(\sin B = 1\)</span>, <span class="math inline">\(B = 90^\circ\)</span> (una solución). 4. Si <span class="math inline">\(\sin B &lt; 1\)</span>, hay dos posibles ángulos: <span class="math inline">\(B_1 = \sin^{-1}(\sin B)\)</span> y <span class="math inline">\(B_2 = 180^\circ - B_1\)</span>. 5. Para cada <span class="math inline">\(B\)</span> válido, calcula <span class="math inline">\(C = 180^\circ - A - B\)</span> y luego <span class="math inline">\(c\)</span>.</p>
<p><strong>Ejemplo:</strong> <span class="math inline">\(a = 10\)</span>, <span class="math inline">\(b = 8\)</span>, <span class="math inline">\(A = 30^\circ\)</span>. Paso 1: <span class="math inline">\(\sin B = \frac{8 \cdot \sin 30^\circ}{10} = \frac{8 \cdot 0.5}{10} = 0.4\)</span>. Paso 2: <span class="math inline">\(\sin B = 0.4 &lt; 1\)</span>. Paso 3: <span class="math inline">\(B_1 = \sin^{-1}(0.4) \approx 23.58^\circ\)</span>, <span class="math inline">\(B_2 = 180^\circ - 23.58^\circ = 156.42^\circ\)</span>. Paso 4: Para <span class="math inline">\(B_1\)</span>, <span class="math inline">\(C = 180^\circ - 30^\circ - 23.58^\circ = 126.42^\circ\)</span>. Para <span class="math inline">\(B_2\)</span>, <span class="math inline">\(C = 180^\circ - 30^\circ - 156.42^\circ = -6.42^\circ\)</span> (invalido). Solucion: <span class="math inline">\(B = 23.58^\circ\)</span>. <strong>Ahora aplica el algoritmo para verificar que <span class="math inline">\(B_2\)</span> no es valido.</strong></p>
<p><strong>Ejercicios:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(a = 15\)</span> cm, <span class="math inline">\(b = 10\)</span> cm, <span class="math inline">\(A = 40^\circ\)</span>. Aplica el algoritmo paso a paso. <strong>[Opcion A: resuelve por escrito. Opcion B: empareja cada paso del algoritmo con su resultado.]</strong> ¿Aplica la regla fija? SI / NO.</p>
<p><strong>Metacognición:</strong> 1. Sin mirar el bloque, escribe la regla fija con tus palabras. 2. ¿Seguiste los pasos del algoritmo en orden? ¿En que paso tuviste duda? 3. Si <span class="math inline">\(a = 5\)</span> cm, <span class="math inline">\(b = 10\)</span> cm y <span class="math inline">\(A = 30^\circ\)</span>, ¿cuántas soluciones tiene el triángulo? Aplica el algoritmo.</p>
<p><strong>Opción de respuesta:</strong> Puedes responder escribiendo, dibujando o explicándoselo a un compañero.</p>
<p><strong>Glosario:</strong> - <strong>Teorema del seno:</strong> igualdad exacta que relaciona los lados de un triángulo con los senos de sus ángulos opuestos. - <strong>Caso ambiguo:</strong> situación donde los datos dados pueden corresponder a cero, uno o dos triángulos distintos. - <strong>Arcoseno (<span class="math inline">\(\sin^{-1}\)</span>):</strong> función inversa del seno que devuelve el ángulo cuyo seno es un número dado.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
</section>
<section id="caracterizados-accesibilidad-sensorial" class="level2 caracterizados" data-number="6.8">
<h2 class="caracterizados anchored" data-number="6.8" data-anchor-id="caracterizados-accesibilidad-sensorial"><span class="header-section-number">6.8</span> Caracterizados — Accesibilidad Sensorial</h2>
<p>Imagina que tienes tres varillas de longitudes <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span> y quieres formar un triángulo. El teorema del seno te dice que si doblas cada varilla en la misma proporción respecto al ángulo que tiene enfrente, todas dan el mismo número. Construye mentalmente un triángulo con tus dedos: pulgar e índice forman un ángulo, y la distancia entre sus puntas es el lado opuesto. Agranda el ángulo: la distancia entre las puntas aumenta. Así funciona el teorema: a mayor ángulo, mayor lado opuesto, en una proporción fija. <strong>Cierra los ojos y describe en voz alta el paso que sigue. Después, señala con el dedo donde escribiste el resultado.</strong></p>
<p><strong>Ejemplo:</strong> Para un triángulo con <span class="math inline">\(A = 35^\circ\)</span>, <span class="math inline">\(B = 55^\circ\)</span>, <span class="math inline">\(a = 6\)</span> cm: 1. <strong>Tacto:</strong> forma un triángulo con tus dedos donde el ángulo <span class="math inline">\(A\)</span> sea pequeño (<span class="math inline">\(35^\circ\)</span>) y <span class="math inline">\(B\)</span> mediano (<span class="math inline">\(55^\circ\)</span>). 2. <strong>Vista:</strong> escribe <span class="math inline">\(A = 35^\circ\)</span>, <span class="math inline">\(B = 55^\circ\)</span>, <span class="math inline">\(a = 6\)</span> cm. 3. <strong>Cálculo:</strong> <span class="math inline">\(C = 180^\circ - 35^\circ - 55^\circ = 90^\circ\)</span>, <span class="math inline">\(b = \frac{6 \cdot \sin 55^\circ}{\sin 35^\circ} \approx 8.57\)</span> cm. 4. <strong>Resultado:</strong> el triángulo tiene un ángulo recto en <span class="math inline">\(C\)</span>. <strong>Ahora cierra los ojos y traza la fórmula con el dedo mientras repites los pasos en voz alta.</strong></p>
<p><strong>Ejercicios:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 25^\circ\)</span>, <span class="math inline">\(C = 85^\circ\)</span>, <span class="math inline">\(a = 4\)</span> cm. Halla <span class="math inline">\(c\)</span> usando tus dedos para visualizar. <strong>[Opcional: responde por voz en vez de escribir.]</strong></p>
<p><strong>Metacognición:</strong> 1. Describe con una imagen mental: ¿cómo se ve, se oye o se siente que el lado crece cuando el ángulo crece? 2. Si cerraras los ojos y solo usaras el tacto, ¿cómo sabrías qué lado es el más largo? 3. La fórmula dice <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B}\)</span>. Si cambia <span class="math inline">\(A\)</span>, ¿cómo cambia la sensación del triángulo?</p>
<p><strong>Opción de respuesta:</strong> Puedes responder escribiendo, grabando un audio o explicándoselo a un compañero.</p>
<p><strong>Glosario:</strong> - <strong>Seno:</strong> valor numérico que crece cuando el ángulo crece (de <span class="math inline">\(0\)</span> a <span class="math inline">\(1\)</span> entre <span class="math inline">\(0^\circ\)</span> y <span class="math inline">\(90^\circ\)</span>). - <strong>Ángulo opuesto:</strong> el ángulo que está frente al lado, como el vértice de un triángulo de papel. - <strong>Resolver:</strong> encontrar los valores faltantes del triángulo usando las reglas.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
</section>
<section id="caracterizados-socioemocional" class="level2 caracterizados" data-number="6.9">
<h2 class="caracterizados anchored" data-number="6.9" data-anchor-id="caracterizados-socioemocional"><span class="header-section-number">6.9</span> Caracterizados — Socioemocional</h2>
<p>Imagina que estás en un grupo de trabajo en la Institución Educativa San José de Sincelejo y deben medir el ancho del patio escolar sin usar cinta métrica. Cada persona del grupo propone un método diferente. Al principio hay confusión, pero luego alguien recuerda que con un transportador y el teorema del seno pueden hacerlo. En matemáticas, como en el trabajo en equipo, hay múltiples caminos para llegar a la misma respuesta, y la clave está en encontrar la relación correcta entre lo que sabes y lo que necesitas descubrir. El teorema del seno te da esa relación constante: no importa qué par de datos tengas, siempre puedes encontrar los que faltan si sigues la proporción. <strong>Antes de seguir, respira profundo 3 veces. Ya tienes esto.</strong></p>
<p><strong>Ejemplo:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 42^\circ\)</span>, <span class="math inline">\(C = 73^\circ\)</span>, <span class="math inline">\(b = 11\)</span> cm. Primero <span class="math inline">\(B = 180^\circ - 42^\circ - 73^\circ = 65^\circ\)</span>. Luego <span class="math inline">\(a = \frac{11 \cdot \sin 42^\circ}{\sin 65^\circ} \approx 8.12\)</span> cm y <span class="math inline">\(c = \frac{11 \cdot \sin 73^\circ}{\sin 65^\circ} \approx 11.69\)</span> cm. Es como si en el grupo cada quien aportara su dato y juntos encontraran la respuesta. <strong>Ahora explica en voz alta el paso que entendiste mejor. No importa si no es perfecto — estás aprendiendo, y cada paso cuenta.</strong></p>
<p><strong>Ejercicios:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(B = 50^\circ\)</span>, <span class="math inline">\(C = 60^\circ\)</span>, <span class="math inline">\(a = 7\)</span> cm. Halla <span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span>. <strong>[Opcional: resuelve en pareja con un compañero.]</strong> Al terminar, en una escala del 1 al 5, ¿cómo te sentiste al resolverlo?</p>
<p><strong>Metacognición:</strong> 1. Explica con tus palabras y sin apuro: ¿por qué el teorema del seno funciona para cualquier triángulo? Si no te sale perfecto, está bien. 2. ¿Cómo se aplica el concepto de proporción constante a situaciones de tu vida donde hay algo que siempre se mantiene igual aunque todo lo demás cambie? 3. ¿Qué estrategia usaste cuando algo se ponía difícil? ¿Funcionó?</p>
<p><strong>Opción de respuesta:</strong> Puedes responder escribiendo, dibujando o explicándoselo a un compañero.</p>
<p><strong>Glosario:</strong> - <strong>Proporción constante:</strong> relación que no cambia, como la confianza en un equipo de trabajo bien coordinado. - <strong>Resolver:</strong> encontrar soluciones paso a paso, como en la vida, donde cada problema tiene una solución si encuentras la relación correcta. - <strong>Triángulo:</strong> figura de tres lados, como tres personas trabajando juntas.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
</section>
<section id="ejemplo-nivel-bajo" class="level2 ejemplo" data-number="6.10">
<h2 class="ejemplo anchored" data-number="6.10" data-anchor-id="ejemplo-nivel-bajo"><span class="header-section-number">6.10</span> Ejemplo — Nivel Bajo</h2>
<p><strong>Regla fija:</strong> En cualquier triángulo <span class="math inline">\(ABC\)</span> se cumple que <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}\)</span>.</p>
<p><strong>Enunciado:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, se conocen los ángulos <span class="math inline">\(A = 30^\circ\)</span>, <span class="math inline">\(B = 45^\circ\)</span> y el lado <span class="math inline">\(a = 10\)</span> cm. Halla el lado <span class="math inline">\(b\)</span>.</p>
<p><strong>Justificación Teórica:</strong> Como conocemos dos ángulos y un lado (AAL), primero encontramos el tercer ángulo y luego aplicamos el teorema del seno usando la proporción que relaciona los lados <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> con sus ángulos opuestos.</p>
<p><strong>Ejecución:</strong></p>
<p><strong>Paso 1: Calcular el ángulo <span class="math inline">\(C\)</span></strong></p>
<p><span class="math display">\[C = 180^\circ - A - B = 180^\circ - 30^\circ - 45^\circ = 105^\circ\]</span></p>
<p><strong>Paso 2: Aplicar el teorema del seno para hallar <span class="math inline">\(b\)</span></strong></p>
<p><span class="math display">\[\frac{a}{\sin A} = \frac{b}{\sin B} \quad\Rightarrow\quad b = \frac{a \cdot \sin B}{\sin A}\]</span></p>
<p><span class="math display">\[b = \frac{10 \cdot \sin 45^\circ}{\sin 30^\circ} = \frac{10 \cdot \frac{\sqrt{2}}{2}}{\frac{1}{2}} = 10\sqrt{2} \approx 14.14\ \text{cm}\]</span></p>
<p><strong>Paso 3: Verificar coherencia</strong></p>
<p>El ángulo <span class="math inline">\(B = 45^\circ\)</span> es mayor que <span class="math inline">\(A = 30^\circ\)</span>, y el lado <span class="math inline">\(b \approx 14.14\)</span> cm es mayor que <span class="math inline">\(a = 10\)</span> cm. Esto es consistente: a mayor ángulo, mayor lado opuesto.</p>
<p><strong>Resultado:</strong> El lado <span class="math inline">\(b\)</span> mide aproximadamente <span class="math inline">\(14.14\)</span> cm <span class="citation" data-cites="stewart2015precalculo">(<a href="../bibliografia.html#ref-stewart2015precalculo" role="doc-biblioref">Stewart et&nbsp;al. 2015</a>)</span>.</p>
</section>
<section id="ejemplo-nivel-medio" class="level2 ejemplo" data-number="6.11">
<h2 class="ejemplo anchored" data-number="6.11" data-anchor-id="ejemplo-nivel-medio"><span class="header-section-number">6.11</span> Ejemplo — Nivel Medio</h2>
<p><strong>Analogía:</strong> El teorema del seno es como una balanza de tres platillos: los tres lados, cada uno dividido por el seno de su ángulo opuesto, pesan lo mismo.</p>
<p><strong>Enunciado:</strong> Desde la cima de una montaña en el Parque Nacional Natural Cocuy (Boyacá), un excursionista mide los ángulos de depresión hacia dos refugios en el valle. El ángulo hacia el refugio A es <span class="math inline">\(38^\circ\)</span> y hacia el refugio B es <span class="math inline">\(52^\circ\)</span>. La distancia entre los dos refugios es de <span class="math inline">\(1.2\)</span> km. ¿A qué distancia está el excursionista del refugio A?</p>
<p><strong>Justificación Teórica:</strong> Se forma un triángulo donde la cima es el vértice <span class="math inline">\(C\)</span> y los refugios son <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span>. El lado <span class="math inline">\(c = 1.2\)</span> km es la distancia entre refugios, opuesto al vértice <span class="math inline">\(C\)</span>. Los ángulos en <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> son los ángulos de depresión desde la cima.</p>
<p><strong>Ejecución:</strong></p>
<p><strong>Paso 1: Identificar los ángulos del triángulo</strong></p>
<p><span class="math display">\[C = 180^\circ - 38^\circ - 52^\circ = 90^\circ\]</span></p>
<p><strong>Paso 2: Aplicar el teorema del seno para hallar <span class="math inline">\(a\)</span> (distancia del refugio A a la cima)</strong></p>
<p><span class="math display">\[\frac{a}{\sin A} = \frac{c}{\sin C} \quad\Rightarrow\quad a = \frac{c \cdot \sin A}{\sin C}\]</span></p>
<p><span class="math display">\[a = \frac{1.2 \cdot \sin 38^\circ}{\sin 90^\circ} = \frac{1.2 \cdot 0.6157}{1} \approx 0.739\ \text{km}\]</span></p>
<p><strong>Paso 3: Verificar coherencia</strong></p>
<p>El triángulo es rectángulo en <span class="math inline">\(C\)</span>, y la distancia <span class="math inline">\(a \approx 0.74\)</span> km es menor que <span class="math inline">\(c = 1.2\)</span> km porque el ángulo <span class="math inline">\(A = 38^\circ\)</span> es menor que <span class="math inline">\(B = 52^\circ\)</span>.</p>
<p><strong>Resultado:</strong> El excursionista está a aproximadamente <span class="math inline">\(0.74\)</span> km del refugio A <span class="citation" data-cites="young2018fisica">(<a href="../bibliografia.html#ref-young2018fisica" role="doc-biblioref">Young y Freedman 2018</a>)</span>.</p>
</section>
<section id="ejemplo-nivel-alto" class="level2 ejemplo" data-number="6.12">
<h2 class="ejemplo anchored" data-number="6.12" data-anchor-id="ejemplo-nivel-alto"><span class="header-section-number">6.12</span> Ejemplo — Nivel Alto</h2>
<p><strong>Formato accesible:</strong> En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(a\)</span> es el lado opuesto al vértice <span class="math inline">\(A\)</span>, <span class="math inline">\(b\)</span> al vértice <span class="math inline">\(B\)</span>, <span class="math inline">\(c\)</span> al vértice <span class="math inline">\(C\)</span>. El teorema del seno relaciona cada lado con el seno de su ángulo opuesto.</p>
<p><strong>Enunciado:</strong> En un triángulo <span class="math inline">\(ABC\)</span> se conocen los lados <span class="math inline">\(a = 12\)</span> cm, <span class="math inline">\(b = 8\)</span> cm y el ángulo <span class="math inline">\(A = 35^\circ\)</span>. Determina: (a) el ángulo <span class="math inline">\(B\)</span>, (b) el ángulo <span class="math inline">\(C\)</span>, (c) el lado <span class="math inline">\(c\)</span>. Considera el caso ambiguo.</p>
<p><strong>Justificación Teórica:</strong> Este es el caso LLA (dos lados y un ángulo no comprendido). Se calcula <span class="math inline">\(\sin B\)</span> a partir de la proporción y se evalúa si hay una, dos o ninguna solución.</p>
<p><strong>Ejecución:</strong></p>
<p><strong>Paso 1: Aplicar el teorema del seno para hallar <span class="math inline">\(\sin B\)</span></strong></p>
<p><span class="math display">\[\frac{a}{\sin A} = \frac{b}{\sin B} \quad\Rightarrow\quad \sin B = \frac{b \cdot \sin A}{a}\]</span></p>
<p><span class="math display">\[\sin B = \frac{8 \cdot \sin 35^\circ}{12} = \frac{8 \cdot 0.5736}{12} \approx 0.3824\]</span></p>
<p><strong>Paso 2: Evaluar el caso ambiguo</strong></p>
<p><span class="math inline">\(\sin B = 0.3824 &lt; 1\)</span> y <span class="math inline">\(b = 8 &lt; a = 12\)</span> (<span class="math inline">\(a \geq b\)</span>), por lo tanto hay una única solución.</p>
<p><span class="math display">\[B = \sin^{-1}(0.3824) \approx 22.48^\circ\]</span></p>
<p><strong>Paso 3: Calcular <span class="math inline">\(C\)</span> y <span class="math inline">\(c\)</span></strong></p>
<p><span class="math display">\[C = 180^\circ - A - B = 180^\circ - 35^\circ - 22.48^\circ = 122.52^\circ\]</span></p>
<p><span class="math display">\[\frac{a}{\sin A} = \frac{c}{\sin C} \quad\Rightarrow\quad c = \frac{a \cdot \sin C}{\sin A}\]</span></p>
<p><span class="math display">\[c = \frac{12 \cdot \sin 122.52^\circ}{\sin 35^\circ} = \frac{12 \cdot 0.8435}{0.5736} \approx 17.65\ \text{cm}\]</span></p>
<p><strong>Paso 4: Verificar coherencia</strong></p>
<p>El lado <span class="math inline">\(b = 8\)</span> cm es menor que <span class="math inline">\(a = 12\)</span> cm, y el ángulo <span class="math inline">\(B \approx 22.48^\circ\)</span> es menor que <span class="math inline">\(A = 35^\circ\)</span>. Consistente. <span class="math inline">\(C\)</span> es el ángulo más grande y <span class="math inline">\(c\)</span> es el lado más grande.</p>
<p><strong>Resultado:</strong> (a) <span class="math inline">\(B \approx 22.48^\circ\)</span>, (b) <span class="math inline">\(C \approx 122.52^\circ\)</span>, (c) <span class="math inline">\(c \approx 17.65\)</span> cm. Hay una única solución <span class="citation" data-cites="stewart2015precalculo">(<a href="../bibliografia.html#ref-stewart2015precalculo" role="doc-biblioref">Stewart et&nbsp;al. 2015</a>)</span>.</p>
</section>
<section id="ejercicios-nivel-bajo" class="level2 ejercicios" data-number="6.13">
<h2 class="ejercicios anchored" data-number="6.13" data-anchor-id="ejercicios-nivel-bajo"><span class="header-section-number">6.13</span> Ejercicios — Nivel Bajo</h2>
<p>Aplica la <strong>regla fija</strong>: <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}\)</span>.</p>
<ul>
<li><p>Completar: En el triángulo <span class="math inline">\(ABC\)</span>, si <span class="math inline">\(A = 40^\circ\)</span>, <span class="math inline">\(B = 70^\circ\)</span> y <span class="math inline">\(a = 8\)</span> cm, entonces <span class="math inline">\(C = \underline{\hspace{2cm}}\)</span> y <span class="math inline">\(b = \frac{\underline{\hspace{2cm}} \cdot \sin \underline{\hspace{2cm}}}{\sin \underline{\hspace{2cm}}}\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 31%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dato</th>
<th style="text-align: center;">Valor</th>
<th style="text-align: left;">Fórmula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(A\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{1cm}}\)</span></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(B\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{1cm}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(b = \frac{a \cdot \sin B}{\sin A}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{1cm}}\)</span></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table></li>
<li><p>V/F: El teorema del seno solo se aplica a triángulos rectángulos. (<span class="math inline">\(\hspace{0.5cm}\)</span>)</p></li>
<li><p>Identificación: En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 50^\circ\)</span>, <span class="math inline">\(C = 60^\circ\)</span>, <span class="math inline">\(b = 10\)</span> cm. ¿Cuál es el valor de <span class="math inline">\(B\)</span> y del lado <span class="math inline">\(a\)</span>?</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
</ul>
</section>
<section id="ejercicios-nivel-medio" class="level2 ejercicios" data-number="6.14">
<h2 class="ejercicios anchored" data-number="6.14" data-anchor-id="ejercicios-nivel-medio"><span class="header-section-number">6.14</span> Ejercicios — Nivel Medio</h2>
<p><strong>Analogía:</strong> Recuerda que el teorema del seno es como una balanza de tres platillos: los tres lados divididos por el seno de sus ángulos opuestos siempre se equilibran.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dato conocido</th>
<th style="text-align: right;">Dato buscado</th>
<th style="text-align: left;">Proporción a usar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(a\)</span>, <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span></td>
<td style="text-align: right;"><span class="math inline">\(b\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\underline{\hspace{4cm}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\underline{\hspace{4cm}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\underline{\hspace{4cm}}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p>Respuesta corta: En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(A = 55^\circ\)</span>, <span class="math inline">\(C = 35^\circ\)</span>, <span class="math inline">\(b = 20\)</span> cm. Halla <span class="math inline">\(a\)</span> y <span class="math inline">\(c\)</span>.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p>Aplicación simple: Un topógrafo en el municipio de Sopó (Cundinamarca) necesita medir el ancho de un río. Se coloca en un punto <span class="math inline">\(A\)</span>, camina <span class="math inline">\(30\)</span> m paralelo al río hasta un punto <span class="math inline">\(B\)</span>, y mide los ángulos <span class="math inline">\(A = 70^\circ\)</span> y <span class="math inline">\(B = 55^\circ\)</span> hacia un árbol al otro lado del río. ¿Cuál es el ancho del río desde <span class="math inline">\(A\)</span> hasta el árbol?</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p>Clasificación: Dados los siguientes triángulos, determina si el caso LLA tiene 0, 1 o 2 soluciones posibles: (a) <span class="math inline">\(a = 10\)</span>, <span class="math inline">\(b = 6\)</span>, <span class="math inline">\(A = 30^\circ\)</span>; (b) <span class="math inline">\(a = 5\)</span>, <span class="math inline">\(b = 8\)</span>, <span class="math inline">\(A = 30^\circ\)</span>; (c) <span class="math inline">\(a = 4\)</span>, <span class="math inline">\(b = 4\)</span>, <span class="math inline">\(A = 30^\circ\)</span>.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
</ul>
</section>
<section id="ejercicios-nivel-alto" class="level2 ejercicios" data-number="6.15">
<h2 class="ejercicios anchored" data-number="6.15" data-anchor-id="ejercicios-nivel-alto"><span class="header-section-number">6.15</span> Ejercicios — Nivel Alto</h2>
<p><strong>Formato accesible:</strong> Cada lado y ángulo se nombra explícitamente. Completa la tabla de datos antes de resolver.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Lado</th>
<th style="text-align: right;">Valor</th>
<th style="text-align: left;">Ángulo opuesto</th>
<th style="text-align: right;">Valor del ángulo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(A\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(b\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(B\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(c\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p>Problema abierto: En un triángulo <span class="math inline">\(ABC\)</span>, <span class="math inline">\(a = 15\)</span> cm, <span class="math inline">\(b = 12\)</span> cm y <span class="math inline">\(A = 42^\circ\)</span>. Determina si existe solución y encuentra todos los lados y ángulos posibles. Considera el caso ambiguo.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
<li><p>Análisis de errores: Un estudiante afirma que en un triángulo <span class="math inline">\(ABC\)</span> con <span class="math inline">\(A = 60^\circ\)</span>, <span class="math inline">\(B = 50^\circ\)</span> y <span class="math inline">\(a = 10\)</span> cm, el lado <span class="math inline">\(b\)</span> se calcula como <span class="math inline">\(b = \frac{10 \cdot \sin 60^\circ}{\sin 50^\circ}\)</span>. ¿Es correcto su planteamiento? Si no, explica el error y proporciona la solución correcta.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p></li>
</ul>
</section>
<section id="retos" class="level2 retos" data-number="6.16">
<h2 class="retos anchored" data-number="6.16" data-anchor-id="retos"><span class="header-section-number">6.16</span> Retos</h2>
<p>El teorema del seno se aplica en la navegación marítima, la topografía, la astronomía y la ingeniería civil. Para este reto:</p>
<ul>
<li>Diseña un cartel informativo que explique el teorema del seno, incluyendo el caso ambiguo (LLA), con un ejemplo paso a paso de un triángulo de tu elección. Usa colores para identificar los lados y sus ángulos opuestos.</li>
<li>Construye un modelo físico con pitillos o palitos de balso y un transportador que represente un triángulo oblicuángulo. Mide los lados y ángulos, y verifica experimentalmente que se cumple el teorema del seno.</li>
<li>Prepara una breve exposición (máximo 3 minutos) explicando cómo los topógrafos del IGAC usan la triangulación y el teorema del seno para medir distancias inaccesibles en el territorio colombiano.</li>
</ul>
</section>
<section id="aplicación-vida-real" class="level2 aplicacion" data-number="6.17">
<h2 class="aplicacion anchored" data-number="6.17" data-anchor-id="aplicación-vida-real"><span class="header-section-number">6.17</span> Aplicación — Vida real</h2>
<p>En la construcción del viaducto del Chirajara (Meta), los ingenieros utilizaron triangulación con el teorema del seno para calcular distancias entre puntos de anclaje separados por cañones profundos. La topografía en regiones montañosas como la Cordillera de los Andes colombiana requiere constantemente el uso del teorema del seno: los topógrafos miden dos ángulos desde una línea base conocida y calculan distancias a puntos inaccesibles como el otro lado de un cañón, la cima de una montaña o la altura de un edificio. La próxima vez que veas un mapa del IGAC o uses Google Maps, recuerda que debajo de esas mediciones hay cientos de triángulos resueltos con el teorema del seno.</p>
</section>
<section id="aplicación-laboratorio" class="level2 aplicacion" data-number="6.18">
<h2 class="aplicacion anchored" data-number="6.18" data-anchor-id="aplicación-laboratorio"><span class="header-section-number">6.18</span> Aplicación — Laboratorio</h2>
<p><strong>Objetivo:</strong> Verificar experimentalmente el teorema del seno midiendo los lados y ángulos de un triángulo construido físicamente.</p>
<p><strong>Materiales:</strong> - Regla de <span class="math inline">\(30\)</span> cm - Transportador - <span class="math inline">\(3\)</span> pitillos rectos - Pegamento o cinta adhesiva - Hoja de papel blanco - Lápiz</p>
<p><strong>Procedimiento:</strong></p>
<p><em>Preparación:</em> 1. Corta los pitillos en tres longitudes diferentes: <span class="math inline">\(a = 12\)</span> cm, <span class="math inline">\(b = 9\)</span> cm, <span class="math inline">\(c = 7\)</span> cm. 2. Une los extremos con pegamento o cinta para formar un triángulo. 3. Coloca el triángulo sobre la hoja de papel y calca su contorno con lápiz.</p>
<p><em>Medición:</em> 4. Con el transportador, mide los tres ángulos del triángulo (<span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(C\)</span>) con la mayor precisión posible. 5. Registra las medidas en la tabla.</p>
<p><em>Verificación:</em> 6. Calcula <span class="math inline">\(\frac{a}{\sin A}\)</span>, <span class="math inline">\(\frac{b}{\sin B}\)</span> y <span class="math inline">\(\frac{c}{\sin C}\)</span> usando los valores medidos. 7. Compara los tres resultados.</p>
<p><strong>Resultados:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Lado</th>
<th style="text-align: center;">Longitud (cm)</th>
<th style="text-align: center;">Ángulo opuesto</th>
<th style="text-align: center;"><span class="math inline">\(\sin\)</span> del ángulo</th>
<th style="text-align: center;"><span class="math inline">\(\frac{\text{lado}}{\sin\text{ángulo}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(12\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(b\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(7\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\underline{\hspace{2cm}}\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Conclusión:</strong> ¿Los tres cocientes fueron aproximadamente iguales? Explica las posibles fuentes de error.</p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
<p><span class="math inline">\(\underline{\hspace{6cm}}\)</span></p>
</section>
<section id="evaluación-tipo-icfes" class="level2 evaluacion" data-number="6.19">
<h2 class="evaluacion anchored" data-number="6.19" data-anchor-id="evaluación-tipo-icfes"><span class="header-section-number">6.19</span> Evaluación — Tipo ICFES</h2>
<p><strong>Pregunta 1 🟢</strong></p>
<p>En el Instituto Geográfico Agustín Codazzi (IGAC) se realiza una medición topográfica. Desde un punto <span class="math inline">\(A\)</span> se mide un ángulo de <span class="math inline">\(40^\circ\)</span> hacia un punto <span class="math inline">\(B\)</span>, y desde <span class="math inline">\(B\)</span> se mide un ángulo de <span class="math inline">\(70^\circ\)</span> hacia el punto <span class="math inline">\(C\)</span>. La distancia entre <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> es de <span class="math inline">\(50\)</span> m. ¿Cuál es la distancia entre <span class="math inline">\(B\)</span> y <span class="math inline">\(C\)</span>?</p>
<div class="icfes-grid">
<div class="icfes-opcion">
<span class="icfes-letra">A</span><span class="icfes-texto"><span class="math inline">\(50 \cdot \frac{\sin 40^\circ}{\sin 70^\circ}\)</span> m</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">B</span><span class="icfes-texto"><span class="math inline">\(50 \cdot \frac{\sin 70^\circ}{\sin 40^\circ}\)</span> m</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">C</span><span class="icfes-texto"><span class="math inline">\(50 \cdot \frac{\sin 50^\circ}{\sin 70^\circ}\)</span> m</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">D</span><span class="icfes-texto"><span class="math inline">\(50 \cdot \frac{\sin 40^\circ}{\sin 50^\circ}\)</span> m</span>
</div>
</div>
<hr>
<p><strong>Pregunta 2 🟢</strong></p>
<p>En un triángulo <span class="math inline">\(ABC\)</span>, se cumple que <span class="math inline">\(\frac{a}{\sin A} = \frac{b}{\sin B} = \frac{c}{\sin C}\)</span>. Si se duplica la longitud del lado <span class="math inline">\(a\)</span> sin cambiar el ángulo <span class="math inline">\(A\)</span>, ¿qué ocurre con la constante <span class="math inline">\(\frac{a}{\sin A}\)</span>?</p>
<div class="icfes-grid">
<div class="icfes-opcion">
<span class="icfes-letra">A</span><span class="icfes-texto">Se duplica, porque el lado <span class="math inline">\(a\)</span> es el numerador de la fracción</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">B</span><span class="icfes-texto">Se reduce a la mitad, porque la relación debe mantenerse constante</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">C</span><span class="icfes-texto">Permanece igual, porque <span class="math inline">\(\sin A\)</span> también se duplica</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">D</span><span class="icfes-texto">Se cuadruplica, porque la relación es directamente proporcional al cuadrado del lado</span>
</div>
</div>
<hr>
<p><strong>Pregunta 3 🟡</strong></p>
<p>En la Sierra Nevada de Santa Marta, un biólogo quiere medir la distancia entre dos árboles <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> separados por una quebrada. Se coloca en un punto <span class="math inline">\(C\)</span> y mide: <span class="math inline">\(AC = 25\)</span> m, <span class="math inline">\(BC = 30\)</span> m y el ángulo <span class="math inline">\(C = 50^\circ\)</span> (ángulo comprendido entre <span class="math inline">\(AC\)</span> y <span class="math inline">\(BC\)</span>). ¿Qué afirmación es correcta sobre la distancia <span class="math inline">\(AB\)</span>?</p>
<div class="icfes-grid">
<div class="icfes-opcion">
<span class="icfes-letra">A</span><span class="icfes-texto">Se puede calcular directamente con el teorema del seno porque se conocen dos lados y el ángulo comprendido</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">B</span><span class="icfes-texto">No se puede calcular porque el problema tiene demasiados datos</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">C</span><span class="icfes-texto">Se calcula con el teorema del seno usando <span class="math inline">\(AB = \frac{25 \cdot \sin 50^\circ}{\sin B}\)</span></span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">D</span><span class="icfes-texto">No se puede calcular directamente con el teorema del seno porque no se conoce ningún lado con su ángulo opuesto</span>
</div>
</div>
<hr>
<p><strong>Pregunta 4 🟡</strong></p>
<p>Dado un triángulo <span class="math inline">\(ABC\)</span> con <span class="math inline">\(a = 8\)</span> cm, <span class="math inline">\(b = 10\)</span> cm y <span class="math inline">\(A = 30^\circ\)</span>, un estudiante calcula <span class="math inline">\(\sin B = \frac{10 \cdot \sin 30^\circ}{8} = 0.625\)</span>. ¿Cuántas soluciones tiene este triángulo?</p>
<div class="icfes-grid">
<div class="icfes-opcion">
<span class="icfes-letra">A</span><span class="icfes-texto">Una solución, porque <span class="math inline">\(a &lt; b\)</span> implica una única posibilidad</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">B</span><span class="icfes-texto">Dos soluciones, porque <span class="math inline">\(a &lt; b\)</span> y <span class="math inline">\(\sin B &lt; 1\)</span></span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">C</span><span class="icfes-texto">Ninguna solución, porque <span class="math inline">\(a &lt; b\)</span> y no se cumple la condición</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">D</span><span class="icfes-texto">Una solución, porque <span class="math inline">\(B = \sin^{-1}(0.625) \approx 38.68^\circ\)</span> es la única posibilidad</span>
</div>
</div>
<hr>
<p><strong>Pregunta 5 🔴</strong></p>
<p>En el Cañón del Chicamocha (Santander), un ingeniero civil diseña un puente colgante. Desde un punto <span class="math inline">\(P\)</span> en una montaña mide un ángulo de <span class="math inline">\(25^\circ\)</span> hacia la torre del puente <span class="math inline">\(T\)</span>, y desde un punto <span class="math inline">\(Q\)</span> a <span class="math inline">\(200\)</span> m de <span class="math inline">\(P\)</span> sobre la misma montaña mide un ángulo de <span class="math inline">\(42^\circ\)</span> hacia la misma torre. Con estos datos se forma el triángulo <span class="math inline">\(PQT\)</span>, donde el ángulo en <span class="math inline">\(T\)</span> es <span class="math inline">\(113^\circ\)</span>.</p>
<p>¿Cuál expresión permite calcular la distancia <span class="math inline">\(PT\)</span> entre el punto <span class="math inline">\(P\)</span> y la torre <span class="math inline">\(T\)</span>?</p>
<div class="icfes-grid">
<div class="icfes-opcion">
<span class="icfes-letra">A</span><span class="icfes-texto"><span class="math inline">\(200 \cdot \frac{\sin 42^\circ}{\sin 113^\circ}\)</span> m</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">B</span><span class="icfes-texto"><span class="math inline">\(200 \cdot \frac{\sin 42^\circ}{\sin 25^\circ}\)</span> m</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">C</span><span class="icfes-texto"><span class="math inline">\(200 \cdot \frac{\sin 25^\circ}{\sin 42^\circ}\)</span> m</span>
</div>
<div class="icfes-opcion">
<span class="icfes-letra">D</span><span class="icfes-texto"><span class="math inline">\(200 \cdot \frac{\sin 113^\circ}{\sin 42^\circ}\)</span> m</span>
</div>
</div>
<hr>
<p><strong>Autoevaluación:</strong></p>
<ol type="1">
<li>¿Qué pregunta te resultó más fácil? ¿Por qué?</li>
<li>¿Qué pregunta te resultó más difícil? ¿Qué harías diferente?</li>
<li>En una escala del 1 al 5, ¿qué tan seguro te sientes aplicando el teorema del seno?</li>
</ol>
</section>
<section id="socialización" class="level2 evaluacion" data-number="6.20">
<h2 class="evaluacion anchored" data-number="6.20" data-anchor-id="socialización"><span class="header-section-number">6.20</span> Socialización</h2>
<p><strong>Pregunta 1 🟢</strong> <em>Competencia:</em> Interpretación <em>Afirmación:</em> Identifica la proporción correcta del teorema del seno para resolver un triángulo AAL. <em>Evidencia:</em> Reconoce que dados dos ángulos y el lado entre ellos, se aplica la proporción adecuada del teorema del seno. <em>Respuesta correcta:</em> A <em>Explicación:</em> En el triángulo <span class="math inline">\(ABC\)</span>, el ángulo en <span class="math inline">\(C\)</span> es <span class="math inline">\(180^\circ - 40^\circ - 70^\circ = 70^\circ\)</span>. <span class="math inline">\(AB = 50\)</span> m está opuesto a <span class="math inline">\(C = 70^\circ\)</span>; <span class="math inline">\(BC\)</span> es opuesto a <span class="math inline">\(A = 40^\circ\)</span>. Aplicando el teorema del seno: <span class="math inline">\(\frac{BC}{\sin 40^\circ} = \frac{50}{\sin 70^\circ} \Rightarrow BC = 50 \cdot \frac{\sin 40^\circ}{\sin 70^\circ}\)</span> m. La opción A es la correcta. Las opciones B y D invierten la proporción, y C usa el ángulo equivocado. <em>Fuente:</em> IGAC. “Métodos de triangulación topográfica”. https://www.igac.gov.co/</p>
<p><strong>Pregunta 2 🟢</strong> <em>Competencia:</em> Argumentación <em>Afirmación:</em> Comprende que la constante del teorema del seno es <span class="math inline">\(2R\)</span> y depende de la circunferencia circunscrita. <em>Evidencia:</em> Analiza cómo el cambio en un lado afecta la proporción, reconociendo que <span class="math inline">\(\sin A\)</span> no cambia a menos que el ángulo cambie. <em>Respuesta correcta:</em> A <em>Explicación:</em> Si se duplica <span class="math inline">\(a\)</span> pero el ángulo <span class="math inline">\(A\)</span> permanece igual, entonces <span class="math inline">\(\frac{a}{\sin A}\)</span> se duplica porque <span class="math inline">\(a\)</span> es el numerador y <span class="math inline">\(\sin A\)</span> no cambia. La constante <span class="math inline">\(2R\)</span> cambia porque el triángulo cambia de tamaño. Las opciones B y C son incorrectas porque <span class="math inline">\(\sin A\)</span> no cambia al duplicar <span class="math inline">\(a\)</span>, y D es incorrecta porque la relación no involucra cuadrados. <em>Fuente:</em> Stewart, J. (2015). Precálculo. Cengage Learning.</p>
<p><strong>Pregunta 3 🟡</strong> <em>Competencia:</em> Interpretación <em>Afirmación:</em> Reconoce las limitaciones del teorema del seno y cuándo se requiere el teorema del coseno. <em>Evidencia:</em> Identifica que el teorema del seno requiere un lado y su ángulo opuesto, no cualquier par de lados y ángulo. <em>Respuesta correcta:</em> D <em>Explicación:</em> Con dos lados (<span class="math inline">\(AC\)</span> y <span class="math inline">\(BC\)</span>) y el ángulo comprendido <span class="math inline">\(C = 50^\circ\)</span>, no se puede aplicar directamente el teorema del seno porque no se conoce ningún lado con su ángulo opuesto. Para aplicar el teorema del seno se necesita un par lado-ángulo opuesto. En este caso, primero debe hallarse <span class="math inline">\(AB\)</span> usando el teorema del coseno. Las opciones A y C son incorrectas porque asumen que el teorema del seno se puede aplicar directamente. <em>Fuente:</em> IGAC. “Cartografía básica colombiana”. https://www.igac.gov.co/</p>
<p><strong>Pregunta 4 🟡</strong> <em>Competencia:</em> Proposición <em>Afirmación:</em> Determina el número de soluciones en el caso ambiguo (LLA) del teorema del seno. <em>Evidencia:</em> Aplica los criterios del caso ambiguo para determinar si hay 0, 1 o 2 soluciones. <em>Respuesta correcta:</em> B <em>Explicación:</em> <span class="math inline">\(a = 8 &lt; b = 10\)</span>, por lo tanto <span class="math inline">\(a &lt; b\)</span>. <span class="math inline">\(\sin B = 0.625 &lt; 1\)</span>. Dado que <span class="math inline">\(a &lt; b\)</span> y <span class="math inline">\(\sin B &lt; 1\)</span>, se cumple <span class="math inline">\(b\sin A &lt; a &lt; b\)</span>, que es la condición para dos soluciones: <span class="math inline">\(B_1 \approx 38.68^\circ\)</span> y <span class="math inline">\(B_2 \approx 141.32^\circ\)</span>. Verificando: para <span class="math inline">\(B_1\)</span>, <span class="math inline">\(C = 111.32^\circ\)</span> (válido); para <span class="math inline">\(B_2\)</span>, <span class="math inline">\(C = 8.68^\circ\)</span> (válido, <span class="math inline">\(C &gt; 0\)</span>). Ambas son soluciones válidas. <em>Fuente:</em> Stewart, J. (2015). Precálculo. Cengage Learning.</p>
<p><strong>Pregunta 5 🔴</strong> <em>Competencia:</em> Argumentación <em>Afirmación:</em> Evalúa argumentos geométricos usando el teorema del seno en un contexto real de ingeniería. <em>Evidencia:</em> Construye el modelo geométrico del problema, identificando correctamente los ángulos del triángulo y aplicando la proporción adecuada. <em>Respuesta correcta:</em> A <em>Explicación:</em> En el triángulo <span class="math inline">\(PQT\)</span>, <span class="math inline">\(PQ = 200\)</span> m está opuesto a <span class="math inline">\(T = 113^\circ\)</span>; <span class="math inline">\(PT\)</span> está opuesto a <span class="math inline">\(Q = 42^\circ\)</span>. Aplicando el teorema del seno: <span class="math inline">\(\frac{PT}{\sin 42^\circ} = \frac{200}{\sin 113^\circ} \Rightarrow PT = 200 \cdot \frac{\sin 42^\circ}{\sin 113^\circ}\)</span> m. La opción A es la correcta. Las opciones B y C usan ángulos incorrectos, y la opción D invierte la proporción. <em>Fuente:</em> INVIAS. “Manual de diseño de puentes en Colombia”. https://www.invias.gov.co/</p>
</section>
<section id="socioemocional" class="level2 socioemocional" data-number="6.21">
<h2 class="socioemocional anchored" data-number="6.21" data-anchor-id="socioemocional"><span class="header-section-number">6.21</span> Socioemocional</h2>
<p>Al aprender el teorema del seno, es normal sentirse abrumado por las fórmulas, los casos ambiguos y las comprobaciones. La clave está en la <strong>Regulación Emocional</strong> (Ley 2503 de 2025): reconocer que la confusión inicial es parte del proceso y que cada triángulo resuelto fortalece tu pensamiento lógico. El teorema del seno nos enseña que, aunque no conozcamos todos los datos de una situación, siempre hay una relación constante que nos permite encontrar lo que falta. Así como en la vida, cuando identificamos lo que sabemos y lo relacionamos correctamente con lo que queremos saber, podemos resolver cualquier problema. Respira, organiza tus datos como organizas los lados y ángulos, y verás que la solución llega.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-stewart2015precalculo" class="csl-entry" role="listitem">
Stewart, James, Lothar Redlin, y Saleem Watson. 2015. <em>Precálculo: Matemáticas para el cálculo</em>. 6.ª ed. Cengage Learning.
</div>
<div id="ref-young2018fisica" class="csl-entry" role="listitem">
Young, Hugh D., y Roger A. Freedman. 2018. <em>Física universitaria con física moderna 1</em>. 14.ª ed. Pearson Educación de México, S.A. de C.V.
</div>
</div>
</section>

</main> <!-- /main -->
<style id="accordion-fouc">
section.level2.teoria > :not(h2),
section.level2.ideas-previas > :not(h2),
section.level2.contexto > :not(h2),
section.level2.caracterizados > :not(h2),
section.level2.retos > :not(h2),
section.level2.socioemocional > :not(h2),
section.level2.ejercicios > :not(h2),
section.level2.aplicacion > :not(h2),
section.level2.ejemplo > :not(h2),
section.level2.evaluacion > :not(h2),
section.level2.simulador > :not(h2) {
  display: none;
}
</style>
<script>
document.addEventListener('DOMContentLoaded', function () {
  if (document.getElementById('accordion-body')) return;

  var TARGET = [
    'teoria', 'ideas-previas', 'contexto', 'caracterizados',
    'retos', 'socioemocional', 'ejercicios', 'aplicacion',
    'ejemplo', 'evaluacion', 'simulador'
  ];
  var SEL = TARGET.map(function (c) { return 'section.level2.' + c; }).join(',');
  var sections = document.querySelectorAll(SEL);
  if (!sections.length) return;

  var parent = sections[0].parentNode;
  var accordion = document.createElement('div');
  accordion.id = 'accordion-body';
  parent.insertBefore(accordion, sections[0]);

  for (var i = sections.length - 1; i >= 0; i--) {
    var section = sections[i];
    var heading = section.querySelector('h2');
    if (!heading) continue;

    var body = document.createElement('div');
    body.className = 'collapse';
    body.id = 'acc-section-' + i;

    var children = Array.from(section.children);
    for (var j = 0; j < children.length; j++) {
      if (children[j] !== heading) {
        body.appendChild(children[j]);
      }
    }

    section.appendChild(body);
    heading.classList.add('accordion-toggle', 'collapsed');
    heading.setAttribute('role', 'button');
    heading.setAttribute('tabindex', '0');
    heading.setAttribute('aria-expanded', 'false');
    heading.setAttribute('aria-controls', body.id);
    body.setAttribute('role', 'region');
    body.setAttribute('aria-labelledby', heading.id);

    accordion.insertBefore(section, accordion.firstChild);

    body.style.display = '';
  }

  var refs = document.getElementById('refs');
  if (refs) {
    var refsParent = refs.closest('.collapse');
    if (refsParent) {
      accordion.parentNode.insertBefore(refs, accordion.nextSibling);
    }
  }

  var foucStyle = document.getElementById('accordion-fouc');
  if (foucStyle) foucStyle.remove();

  function toggleSection(h2) {
    var section = h2.closest('section.level2');
    if (!section) return;
    var body = section.querySelector('.collapse');
    if (!body) return;

    var isOpen = body.classList.contains('show');

    accordion.querySelectorAll('.collapse.show').forEach(function (c) {
      c.classList.remove('show');
    });
    accordion.querySelectorAll('.accordion-toggle').forEach(function (t) {
      t.classList.add('collapsed');
      t.setAttribute('aria-expanded', 'false');
    });

    if (!isOpen) {
      body.classList.add('show');
      h2.classList.remove('collapsed');
      h2.setAttribute('aria-expanded', 'true');
    }
  }

    document.addEventListener('click', function (e) {
    var h2 = e.target.closest('.accordion-toggle');
    if (h2) toggleSection(h2);
  });

  document.addEventListener('keydown', function (e) {
    if (e.key !== 'Enter' && e.key !== ' ') return;
    var h2 = e.target.closest('.accordion-toggle');
    if (h2) {
      e.preventDefault();
      toggleSection(h2);
    }
  });

  var tooltipMap = {
    'Source Code': 'Código fuente',
    'Download': 'Descargar',
    'Share': 'Compartir',
    'Download PDF': 'Descargar PDF',
    'Download ePub': 'Descargar ePub'
  };
  document.querySelectorAll('.sidebar-tools a[title]').forEach(function (a) {
    var en = a.getAttribute('title');
    if (tooltipMap[en]) a.setAttribute('title', tooltipMap[en]);
    var label = a.getAttribute('aria-label');
    if (tooltipMap[label]) a.setAttribute('aria-label', tooltipMap[label]);
  });
  document.querySelectorAll('.sidebar-tools .menu-text').forEach(function (span) {
    if (tooltipMap[span.textContent]) span.textContent = tooltipMap[span.textContent];
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/camilotayac\.github\.io\/docere\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../06_Decimo/escritura_quimica.html" class="pagination-link" aria-label="Escritura de ecuaciones químicas">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Escritura de ecuaciones químicas</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../bibliografia.html" class="pagination-link" aria-label="Referencias">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Referencias</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2025, Camilo Tayac</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/camilotayac/docere/edit/main/06_Decimo/teorema_del_seno.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>