on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - run: quarto render --to html --to pdf --to epub
        working-directory: ./liber
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./liber/_book
      - id: deployment
        uses: actions/deploy-pages@v4
